### ISSUE TITLE
PhET Black Box: Can we gray out investigate wires that are inside the black box and vice versa?

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#107]

**Comment by samreid** [comment]
Or gray out the images?

**Comment by samreid** [comment]
@kathy-phet suggests changing the background when in build mode to indicate you are supposed to build inside the box.

**Comment by samreid** [comment]
@arouinfar will supply grayscale images

**Comment by arouinfar** [comment]
Self-assigning so I remember to get these to @samreid tomorrow.

**Comment by samreid** [comment]
I made changes above to support the new overlay pattern.  While I was there, I made disabled components have 0.5 opacity just to see how it looks (even though we agreed we would try grayscale).  It seems pretty good in the normal case:

![image](https://cloud.githubusercontent.com/assets/679486/15417824/06e74528-1e17-11e6-96d4-fd788005aca3.png)

However it does suffer from the problem I mentioned if components are overlapping:

![image](https://cloud.githubusercontent.com/assets/679486/15417832/2198daee-1e17-11e6-8d9f-f252838b82f7.png)

I do not think it will take too long (1-2 hours) to add grayscale images for all component types, but I thought I'd raise this current version as a possibility in case it is good enough for now.

**Comment by samreid** [comment]
By the way, another benefit of this approach is that the light bulb lines will now be comparable.  Instead of being behind a semi-transparent overlay, the light bulb brightness lines will shine and they can be full color, so comparisons will be easier (was muddled behind the overlay).

**Comment by samreid** [comment]
@arouinfar I'm finished with all other open high priority MVP CCK BB issues, I'd be happy to generate grayscale images and proceed with this issue or happy to wait if you are already on the case.  (I'll wait to hear from you either way).

**Comment by samreid** [comment]
The light bulb nodes from scenery phet are already pretty gray, perhaps we can leave those as-is (also helps with cueing comparable brightness):

![image](https://cloud.githubusercontent.com/assets/679486/15417889/cf6c8a12-1e17-11e6-8e9c-d47853cf733d.png)

If we do decide to grayscale it, it will be a lot of work, since it is a common code component that has already two images (on/off).

**Comment by arouinfar** [comment]
I've emailed grayscale assets for the battery, resistor, and wire to @samreid. However, I think the reduced opacity will work just fine for the MVP.  

No need to change the artwork for the lightbulb -- reduced opacity looks good to me.

I've noticed that the wire stubs attached to the black box now appear gray in Investigate mode, which seems like it may be a byproduct of this change.
![image](https://cloud.githubusercontent.com/assets/8419308/15489225/24800f46-211b-11e6-91f6-bd8012112f23.png)

Not sure if this is related, but I've also noticed that the solder layer moves to the front when switching from Investigate to Build. Perhaps this is intentional?
![image](https://cloud.githubusercontent.com/assets/8419308/15489284/b8212690-211b-11e6-85e3-afed26229378.png)
![image](https://cloud.githubusercontent.com/assets/8419308/15489276/a5ef46be-211b-11e6-8f38-c329daf56139.png)

**Comment by arouinfar** [comment]
Tagging for design meeting, since we want to get Stanford's opinion on the reduced opacity components.

**Comment by arouinfar** [comment]
Reduced opacity components are preferred for the MVP.

**Comment by samreid** [comment]
@arouinfar will this ever be implemented?  If so, when?

**Comment by arouinfar** [comment]
@samreid, I don't think this won't be implemented for the Stanford study(ies). However, it is a desired feature for the version of CCK: Black Box that we will develop for the PhET site. Given other CCK priorities, I don't think we'll work on the development of Black Box anytime soon.

**Comment by samreid** [comment]
Issue will now be tracked in the black box study repo.
