### ISSUE TITLE
We would like to use the delete/backspace key to delete a selected circuit element

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#114]
@jessegreenberg how would you go about this?

**Comment by jessegreenberg** [comment]
In the base clase for a circuit element node, you could add something like this to get it working with the Parallel DOM.

```js
    // create a custom focus highlight {Node|Shape|Bounds2}
    var focusHighlight = ...

    this.accessibleContent = {
      focusHighlight: focusHighlight,
      createPeer: function( accessibleInstance ) {

        // just a div for now, later we can find a more representative html element
        var domElement = document.createElement( 'div' );

        // add to the navigation order if you wish
        domElement.tabIndex = 0;

        // when the circuit element is selected the dom element should have focus
        circuit.selectedCircuitElementProperty.link( function( lastCircuitElement ) {
          if ( lastCircuitElement === circuitElement ) {
            domElement.focus();
          }
        } );

        // listen for when delete or backspace pressed and remove from circuit
        domElement.addEventListener( 'keydown', function( event ) {
          var keyCode = event.keyCode || event.which;
          if ( keyCode === 46 || keyCode === 8 ) {
            circuit.remove( circuitElement );
          }
        } );

        return new AccessiblePeer( accessibleInstance, domElement );
      }
    }
```

**Comment by samreid** [comment]
Is accessibility still buried behind a query parameter?  If so, how/when could we get this feature from the main version?

**Comment by jessegreenberg** [comment]
This assumes that the node has a reference to the circuit, so maybe there is a better place to have this block.  Also, we will want to dispose the domElement's eventListener.  For now, you will need to add the ```accessibility``` query parameter to try this out, or you could add ```accessibility: true``` in sim options.

**Comment by samreid** [comment]
Will any undesirable/buggy behaviors creep in if I enable accessibility using either of these approaches?  If so, should I just add a global key listener (not in the accessibility framework?)  Or is that really the best long term approach?

**Comment by jessegreenberg** [comment]
In the long term, we will want to do something like the above for accessibility, but it does have a few immediate drawbacks.  If we use the accessibility framework we might want to make sure that keyboard navigation is working for all of the simulation elements since common components will be in the navigation  order already.  We will also want to spend some time making sure that home screen/joist buttons work well with keyboard navigation (joist buttons have not been outfitted yet).

**Comment by jessegreenberg** [comment]
I can't think of any other bugs, it will just mean that we will want to work on some of the above sooner rather than later.  If that is OK, I think using the accessible method is the way to go. Otherwise, a global key listener would be fine.

If you want to use the DOM approach, I can help or collaborate with this at any time!

**Comment by samreid** [comment]
@jessegreenberg I'm getting closer to a good point to work on this.  Can you comment what the best strategy is now?  I'm not sure if the strategy in https://github.com/phetsims/circuit-construction-kit-common/issues/114#issuecomment-222742819 is the best, or if it has been superseded by AccessibleNode or something else.

**Comment by jessegreenberg** [comment]
Yes, now I would recommend AccessibleNode for this feature, it was recently added to Scenery.   The following options might work assuming that CircuitElementNode can access circuit:
```js
    options = _.extend( {
      // options for keyboard navigation
      focusable: true,
      focusHighlight: 'invisible',
      
      events: {
        keydown: function( event ) {
          var code = event.keyCode || event.which;
          if ( code === Input.KEY_DELETE || code === Input.KEY_BACKSPACE ) {
            circuit.remove( circuitElement );
          }
        }
      }
    }, options );
    AccessibleNode.call( this, options );
```

With this approach things like the Reset All button and check boxes will automatically be in the tab navigation order, is this OK?  If you want to disable more general keyboard navigation for now, it should be enough to add this somewhere:

```js
    document.addEventListener( 'keydown', function( event ) {
      var keyCode = event.keyCode || event.which;
      if ( keyCode === Input.KEY_TAB ) {
        event.preventDefault();
      }
    } );
```

**Comment by jessegreenberg** [comment]
@samreid I gave it a shot in the above commit in branch keyboard-delete if you would like to review.  If you have any questions about the changes please let me know.

**Comment by samreid** [comment]
@jessegreenberg this looks great, I'm going to move it to master, delete the branch and follow-up here with questions and comments.

**Comment by samreid** [comment]
The main issues in functionality are:

1. After deleting the element, the focus region remains on the screen
2. There are two competing highlights, yellow and purple.

![select](https://cloud.githubusercontent.com/assets/679486/21559701/2c4cf702-ce0e-11e6-9d7d-c3c739c086bf.gif)

How do we get rid of the focus region?  Should that happen automatically if we the AccessibleNode is disposed?

For the competing highlights, should I (a) tell the accessibility highlight to be invisible and use my pre-existing code (b) move my existing yellow highlight implementation to the accessibility subsystem (c) just use the purple highlight (possibly styled differently) or (c) something else?

**Comment by samreid** [comment]
I can no longer reproduce the bugs in https://github.com/phetsims/circuit-construction-kit-common/issues/114#issuecomment-269731431, perhaps I had a stale AccessibleNode?

**Comment by samreid** [comment]
It would still be good to hear @jessegreenberg's recommendation for this question:

> For the competing highlights, should I (a) tell the accessibility highlight to be invisible and use my pre-existing code (b) move my existing yellow highlight implementation to the accessibility subsystem (c) just use the purple highlight (possibly styled differently) or (c) something else?

**Comment by jessegreenberg** [comment]
> How do we get rid of the focus region? Should that happen automatically if we the AccessibleNode is disposed?

Exactly, sorry about that.  I recently added that in phetsims/scenery@b8c004f99b1f2a1689e9906960a8442dc23189c9, so it is likely AccessibleNode was stale.

> For the competing highlights, should I (a) tell the accessibility highlight to be invisible and use my pre-existing code (b) move my existing yellow highlight implementation to the accessibility subsystem (c) just use the purple highlight (possibly styled differently) or (c) something else?

With option (b) the focus highlights will be in display overlay so it will always be on top of other view elements:
![capture1](https://cloud.githubusercontent.com/assets/6396244/21570950/d4da42ca-ce87-11e6-80f7-d0719dc1a5b9.PNG)

For accessibility we never want to occlude the focus highlight, but the above might not be acceptable in this case.  If keeping the focus highlight above the meters is OK in this sim, then option (b) would be best for consistency and accessibility.  Otherwise, I think option (a) would be best.

**Comment by samreid** [comment]
I'll take a look at using the accessibility overlay for drawing these regions to see how it would work.  Reassigned to me.

**Comment by samreid** [comment]
Unassigning, I'll work on this in my CCK list.

**Comment by samreid** [comment]
@arouinfar can you please review this issue and recommend how to proceed for 1.0?

**Comment by arouinfar** [comment]
@samreid I'm not sure I've followed everything. Are you trying to leverage a11y features to use the delete key to delete circuit components? 

In general, I think it would be really helpful to use the delete key for this. I don't think it would be a required feature for 1.0, but nice to have if time allows. If you think this is something we should discuss with the team, please tag this issue for design meeting, @samreid.

**Comment by samreid** [comment]
The delete key already works for deleting items, the remaining questions are about whether the highlighting should be purple (the built-in accessibility type) or yellow (the current custom cck type), and whether it can be always in front or if it should layer with the objects, see pic in https://github.com/phetsims/circuit-construction-kit-common/issues/114#issuecomment-269810184

**Comment by arouinfar** [comment]
Thanks for the clarification @samreid. I think it's fine to keep the highlight layered on top, as in the screenshot you referenced. I would prefer we keep the yellow highlight, rather than using a11y focus style. If/when CCK is made keyboard accessible, circuit components will have both a focused and "grabbed" state. 

For example, once the balloon in BASE is grabbed, it can be moved around the playarea, and the highlight becomes black:
<img src="https://cloud.githubusercontent.com/assets/8419308/25722245/aed43896-30d0-11e7-8df8-6c0c6f89cb04.png" width=200> <img src="https://cloud.githubusercontent.com/assets/8419308/25722261/bc2a97c4-30d0-11e7-9d3a-2de734b3135d.png" width=200>

When using CCK with a mouse/touch, the yellow highlight comes up once an item is selected. I think  this is akin to a "grabbed" state in BASE. Generally speaking, I think grabbed states tend to have a different color than the focus style.

**Comment by samreid** [comment]
@jessegreenberg and I met and reviewed the accessibility engine and implementation to see how it would be used in Circuit Construction Kit.  By adding startDrag -> self.focus() we can trigger nodes to highlight themselves, and it looks like we could use Display.focusProperty to track the focused items.  However, after our investigation we estimate that it would be much more work to be using the accessibility engine to handle the vertex and circuit element highlights and to do so in a way that doesn't expose half-hearted accessibility throughout the rest of the simulation.  Hence we are recommending to publish 1.0 with the current implementation and wait until we have a week or so to investigate further, perhaps when it is time to do a full accessibility design and implementation for Circuit Construction Kit.

**Comment by samreid** [comment]
I recommend closing this issue since delete/backspace works well, and we will likely need design meetings, more issues and more work to fully instrument for accessibility.
