### ISSUE TITLE
Allow electrons to flow while vertices being dragged.

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#147]
This could be simulated (maybe?) by maintaining phase when relaying out electrons during a drag.

**Comment by samreid** [comment]
My main concern about this is that there is (currently) a significant performance delay when dragging a circuit element.  If we try to run the circuit at full speed while dragging, it could end up looking wrong if it runs slower because it is poor performance.  Still, after experimenting with this, I'm interested in giving it a try, especially if it is not too complicated to implement.

**Comment by samreid** [comment]
It may be easier to hide or pause electrons during drag, but that could look odd or incorrect.

**Comment by samreid** [comment]
Maintaining phase at junctions doesn't sound straightforward.  @arouinfar can you please review this issue and see what you recommend.

**Comment by arouinfar** [comment]
@samreid I'm leaning towards pausing the electrons while dragging, but we can discuss this in design meeting.

**Comment by arouinfar** [comment]
Discussed in 5/4/17 design meeting. We've decided to keep the behavior as-is, which is also consistent with Java.

Pausing electrons seems reasonable because you're in the act of moving around the circuit. The bulb stays lit even though electrons don't appear to flow through it. Turning the bulb off or temporarily hiding the electrons would be alternative options, but seem like they would be more distracting and could cause confusion.

Seems like too much effort to freeze the electrons in the code while dragging, and the current behavior that resets the electrons looks good enough.

Self-assigning to add to Teacher Tips checklist.

**Comment by arouinfar** [comment]
Tracking the teacher tips in https://github.com/phetsims/circuit-construction-kit-dc/issues/41, so I think this issue can be closed.

**Comment by samreid** [comment]
@ariel-phet mentioned he saw this issue again during testing.  It was surprising that the electrons pause when dragging another connected circuit element.  We discussed reopening--perhaps with other model fixes we no longer need the workaround of relayout for the electrons on drag.  But on the other hand, it seemed like it wasn't causing much trouble.

Once the rest of the model is working, we can investigate this.
