### ISSUE TITLE
Electron gaps with short wires

### ISSUE THREAD

**Issue by phet-steele** [phetsims/circuit-construction-kit-common#159]
@arouinfar @samreid the quantity of electrons in a wire depends on the length of the wire, and if the wire is short enough, there are no electrons in the wire:
<img width="277" alt="screen shot 2016-07-07 at 10 42 11 am" src="https://cloud.githubusercontent.com/assets/5863899/16661601/ebd64794-4430-11e6-8531-a764ebf618e4.png">

If a circuit is made with any "short" wires, there are gaps in the electron flow. I made an extreme case below, but more reasonable cases exist:
![cckbb10](https://cloud.githubusercontent.com/assets/5863899/16661689/56546c90-4431-11e6-91c1-38a6c888ecf5.gif)

Seen on OSX 10.11.5 Chrome, for phetsims/tasks/issues/636.

Troubleshooting information:
Name: ‪Circuit Construction Kit: Black Box Study‬
URL: http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.0.0-dev.18/circuit-construction-kit-black-box-study_en.html
Version: 1.0.0-dev.18 2016-07-05 23:04:10 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36
Language: en-US
Window: 1920x1002
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"83211f20","branch":"master"},"babel":{"sha":"452ce1dc","branch":"master"},"brand":{"sha":"f0b1f7da","branch":"master"},"chipper":{"sha":"531f9047","branch":"master"},"circuit-construction-kit":{"sha":"6c44e1b0","branch":"master"},"circuit-construction-kit-black-box-study":{"sha":"85860b42","branch":"master"},"dot":{"sha":"3628c3ae","branch":"master"},"joist":{"sha":"94bc734c","branch":"master"},"kite":{"sha":"88f0c3a0","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"35ef94ad","branch":"master"},"scenery":{"sha":"942889ad","branch":"master"},"scenery-phet":{"sha":"d2906d78","branch":"master"},"sherpa":{"sha":"77506dc3","branch":"master"},"sun":{"sha":"c5dbf7cd","branch":"master"},"tandem":{"sha":"a8ac284b","branch":"master"}}

**Comment by arouinfar** [comment]
Good observation @phet-steele. It looks like this issue is also present in the Java version. Perhaps if we limit wires to have at least one electron (unless their vertices overlap), the problem will be alleviated.

These wires should have at least one electron:
![image](https://cloud.githubusercontent.com/assets/8419308/16663722/6cbd43f4-443a-11e6-81b3-4361b8ba5a5e.png) ![image](https://cloud.githubusercontent.com/assets/8419308/16663736/7665d2ea-443a-11e6-8150-12a5cc8db83d.png) ![image](https://cloud.githubusercontent.com/assets/8419308/16663746/81441d84-443a-11e6-8507-bef943784c5e.png)

And these would have none:
![image](https://cloud.githubusercontent.com/assets/8419308/16663759/90561084-443a-11e6-8bb4-f30c8624c31d.png)![image](https://cloud.githubusercontent.com/assets/8419308/16663771/9d34505e-443a-11e6-9c1b-4c8abe60df0b.png)![image](https://cloud.githubusercontent.com/assets/8419308/16663781/a9b06af2-443a-11e6-83dc-6fede369a888.png)

**Comment by samreid** [comment]
Fixed above, ready for review in next version.

**Comment by phet-steele** [comment]
This is an acceptable solution :smile:
