### ISSUE TITLE
Lightbulb rays go over some of the panels and text boxes

### ISSUE THREAD

**Issue by alynne-phet** [phetsims/circuit-construction-kit-common#161]
For phetsims/tasks#636
Test Device: Personal Laptop
Operating System: Mac OSX 10.11.5
Browser: Chrome

Problem Description: The lightbulb rays go over some of the panels and text boxes. This makes it hard to read/see whatever is below the rays.  

Steps to Reproduce:
1. Create any complete circuit including a lightbulb
2. Change the resistance of the lightbulb to 0 ohms
3. Move the lightbulb over any of the panels and text boxes

Screenshots:
![image](https://cloud.githubusercontent.com/assets/19288972/16667506/09f8e0b0-444a-11e6-912f-34b3e82a0d7a.png)

![image](https://cloud.githubusercontent.com/assets/19288972/16667512/0dfb9cca-444a-11e6-92df-b613c9a78640.png)

![image](https://cloud.githubusercontent.com/assets/19288972/16667522/190eb778-444a-11e6-9c70-7fd05bf06466.png)

Name: ‪Circuit Construction Kit: Black Box Study‬
URL: http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.0.0-dev.18/circuit-construction-kit-black-box-study_en.html
Version: 1.0.0-dev.18 2016-07-05 23:04:10 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36
Language: en-US
Window: 1386x717
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 768
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"83211f20","branch":"master"},"babel":{"sha":"452ce1dc","branch":"master"},"brand":{"sha":"f0b1f7da","branch":"master"},"chipper":{"sha":"531f9047","branch":"master"},"circuit-construction-kit":{"sha":"6c44e1b0","branch":"master"},"circuit-construction-kit-black-box-study":{"sha":"85860b42","branch":"master"},"dot":{"sha":"3628c3ae","branch":"master"},"joist":{"sha":"94bc734c","branch":"master"},"kite":{"sha":"88f0c3a0","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"35ef94ad","branch":"master"},"scenery":{"sha":"942889ad","branch":"master"},"scenery-phet":{"sha":"d2906d78","branch":"master"},"sherpa":{"sha":"77506dc3","branch":"master"},"sun":{"sha":"c5dbf7cd","branch":"master"},"tandem":{"sha":"a8ac284b","branch":"master"}}

**Comment by samreid** [comment]
@arouinfar can you think about the layering of the light rays and the layering of the circuit components?  Should circuit components go in front of text and in front of control panels?  Should light rays go behind  text and control panels?  Should light rays go behind other circuit components?

If we decide that light rays should go behind control panels but circuit components go in front of control panels, then we will need to rewrite the light bulb code so that it shows the light rays in a separate layer.

**Comment by arouinfar** [comment]
Sounds good @samreid. Let's go with circuit components in front of text and control panels, and light rays behind text/panels/components. I don't think this is a critical issue to address before we deliver to Stanford, but if it's a relatively minor change, can you please take care of it?

**Comment by samreid** [comment]
It would be a significant change to separate the layers for light bulb and its rays, so I'll postpone it.

**Comment by arouinfar** [comment]
> @arouinfar is this an essential feature for 1.0 or later?

No need to address for 1.0 @samreid. Tagging for 1.1+.

**Comment by samreid** [comment]
We decided to go for it for 1.0

**Comment by samreid** [comment]
Ready for testing in http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.78/circuit-construction-kit-dc_en.html

@arouinfar can you take a look?

**Comment by arouinfar** [comment]
Looks good @samreid! I noticed that the rays go behind the view selection button, but over the inactive option. I'm not particularly bothered by it, but I thought I'd point it out in case it was an oversight rather than due to some limitation.

![image](https://user-images.githubusercontent.com/8419308/28198096-b27325e6-6818-11e7-9894-e569c7cf45ef.png)

**Comment by samreid** [comment]
The default behavior for radio buttons is to show their selection status by changing the opacity.  It looks like there is an option to change the appearance, but it would take up to an hour to figure out and it would be somewhat unconventional.  Let me know if I should go for it.

**Comment by arouinfar** [comment]
Ooooh, that makes sense! Thanks for the clarification @samreid. No need to make any further changes. Closing.

**Comment by phet-steele** [comment]
@samreid what about text + light rays? dev.160 still has rays that go over the animation speed text while https://github.com/phetsims/circuit-construction-kit-common/issues/161#issuecomment-235824650 suggested rays should go behind the text. I don't see comments in this issue saying otherwise, so is there more work to be done?

**Comment by samreid** [comment]
If I put the "speed throttled" message in the CircuitLayerNode, I can layer it between the light bulb rays and the rest of the circuit, but then it becomes difficult to position correctly and its scale/position will change when zooming in and out.

The two straightforward solutions are (a) put the speed throttled message behind the entire CircuitLayerNode (including circuit elements and light rays) or (b) put the speed throttled message in front of the entire CircuitLayerNode.

@ariel-phet or @arouinfar can you please advise?

**Comment by ariel-phet** [comment]
@samreid it seems for consistency probably best to behave like the "Tap circuit element to edit." text

So I would think (b) is the best option, especially since this message disappears when the battery is no longer on fire.

**Comment by arouinfar** [comment]
> @samreid what about text + light rays? dev.160 still has rays that go over the animation speed text while #161 (comment) suggested rays should go behind the text

Good catch @phet-steele. It's possible that the layering was restructured after this issue was closed, and things got reshuffled a bit. 

@samreid I'd be fine with either (a) or (b), but as @ariel-phet pointed out, (b) would be more consistent with the other text in the play area, so let's go with that.

**Comment by samreid** [comment]
I moved the speed throttling text in front of the CircuitLayerNode, it looks like this now:

![image](https://user-images.githubusercontent.com/679486/30408392-b2e81f4e-98bb-11e7-8132-50da3a25dd66.png)

@arouinfar @phet-steele or @ariel-phet can you please review on phettest?

**Comment by arouinfar** [comment]
Looks good to me @samreid!

**Comment by arouinfar** [comment]
@phet-steele and @lmulhall-phet would also like to review, so leaving it open for them.

**Comment by lmulhall-phet** [comment]
Looks good! 👍
