### ISSUE TITLE
Touch areas should be expanded for toolbox components

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#184]
On iPad3, it is difficult to drag out the components from the toolbox.  We should expand their touch areas and additionally consider swipe-to-grab.

**Comment by samreid** [comment]
@kathy-phet said:

Just tried to check out CCK on my phone. Can you add a swipe to pick up option and increase touch areas?  I could not successfully pull a component from either box. 

Not urgent, just good if we use on touch. 

Thanks!
Kathy 

Sent from my iPhone

**Comment by samreid** [comment]
Touch areas looking much nicer in the above commit:

![image](https://cloud.githubusercontent.com/assets/679486/17164791/c0c8e298-5388-11e6-8582-04dbe20f2375.png)

Works great on my tiny iPhone 5S.

**Comment by samreid** [comment]
I published a version here for testing:
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.0.0-dev.21/circuit-construction-kit-black-box-study_en.html?showPointerAreas

I haven't re-tested the entire app to make sure nothing else was disturbed (though I'm not aware of any in-progress breaking changes), this is mainly to focus on the pointer areas.

@kathy-phet can you try it out and report back?

**Comment by samreid** [comment]
> Can you add a swipe to pick up option

I didn't implement this yet, the input listeners are not written with SimpleDragHandler and I'm not sure how much effort would be required to port.

Also, I didn't increase touch areas for the play area objects yet, just for the toolbox--I may need to do that too.

**Comment by arouinfar** [comment]
@samreid we don't need to be worried about touch areas for Stanford, since they won't be using an iPad for their study. 

The touch area boundaries look good in your screenshot, but I won't have access to an iPad to test until Friday. If you and @kathy-phet are happy with how it feels, then it's fine with me!

**Comment by kathy-phet** [comment]
I've played with the new version, and definitely better for pulling items out of the tool box. 

However, I think we will want to switch the behavior to swipe to pick-up because of the play area behavior. In the playarea, it doesn't work to increase the touch areas because of overlap issues so swipe to pick up makes the most sense to me with only modest increases in touch areas that will not cause overlap problems. 

But - as I said, this is not urgent, just a to-do for later.

**Comment by kathy-phet** [comment]
Changing priority to medium

**Comment by samreid** [comment]
I'll create a new issue for the "swipe to pick up in play area" and close this one.
