### ISSUE TITLE
Create artwork for the objects

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#264]
@arouinfar can you please work with our artist to create artwork for the objects to be used in the 2nd screen?

Note to self: this issue is in common instead of "dc" because we may use the objects in other cck sims.

**Comment by arouinfar** [comment]
Items needed:
* Dollar bill
* Paper clip
* Penny
* Eraser
* Pencil (graphite)
* Hand
* Dog

Before creating a task for our graphic artist, I have a few questions:
* The grab bag items in Java CCK have a photorealistic look. Is this desirable for CCK:DC, or should the style be more in line with our HTML5 aesthetic? I would prefer the latter, though I could see why others may prefer to keep the grab bag items looking more realistic.
* Is it important to use the penny? If we stray from photorealism, the PhET-girl coin used in Expression Exchange and Proportion Playground may be a good replacement. Use of an imaginary currency also adds a bit of whimsy and makes the sim more global. I think the PhET-girl coin has a metallic look and would still be perceived as a conductor.
* What sort of dog should we include? I think it would be a nice nod to @ariel-phet to model the dog after Emmy.

Any thoughts @ariel-phet?

**Comment by ariel-phet** [comment]
@arouinfar we should definitely stay with a style more in line with our HTML5 aesthetic. Nothing in our sims is "photorealistic" anymore, nor should it be.

I think we could have a generalized "coin" (does not need to be a penny)

I am sure Emmy would be fine with being the model...I think Mariah already may have a start to that in some of her artwork.

**Comment by arouinfar** [comment]
> I am sure Emmy would be fine with being the model...I think Mariah already may have a start to that in some of her artwork.

I vaguely remember Mariah creating a cartoon version of you and Emmy, but I had trouble finding it in her artwork folder. @ariel-phet do you remember which issue it was for?

**Comment by ariel-phet** [comment]
@arouinfar I don't see it either...I need to reach out to Mariah anyhow, I will see if I can get in touch with her.

**Comment by arouinfar** [comment]
Thanks @ariel-phet. I will create an artwork task for these items, but hold off on the dog and general coin.

**Comment by arouinfar** [comment]
Artwork is being tracked in https://github.com/phetsims/tasks/issues/833. Unassigning myself for now.

**Comment by samreid** [comment]
As noted in #317 this simulation needs to be feature complete and ready for code review by June 26 in order to meet our "end of July" deadline.  It would be great to have this artwork a month before code review--I could work with placeholders in the meantime but that's not as efficient.  @arouinfar @ariel-phet @kathy-phet can you please update on this status?

**Comment by arouinfar** [comment]
@samreid I've pinged the artist in the artwork task.

**Comment by arouinfar** [comment]
@samreid I've emailed you the assets for the coin, eraser, pencil, and hand. I'll send you the dog and dollar bill as soon as I have them.

**Comment by arouinfar** [comment]
@samreid I have emailed you the latest assets, including the dog and dollar bill. For the dog, I think you'll want to off-set the vertices a bit, otherwise things may look a bit odd. In the carousel, the dog should be upright, but when pulled out, it could remain upright with the vertices offset (middle) or the dog could be rotated a bit so that the vertices are level with one another (bottom).

![image](https://user-images.githubusercontent.com/8419308/26891029-cf11d3ec-4b70-11e7-97ef-aca6caacb515.png)



I've also noticed that the pencil and eraser have been badly exported. The eraser is missing its right-most stroke and the pencil has an extra line below it. I've tweaked the artboard size a bit and have re-exported these assets.

![image](https://user-images.githubusercontent.com/8419308/26890598-5502c7ec-4b6f-11e7-8058-1f928f2a3605.png)

I also find that the Grab Bag items are overly large. Do you need to address #354 before tweaking the size?
![image](https://user-images.githubusercontent.com/8419308/26890686-a4b72206-4b6f-11e7-932d-7381c842ea84.png)

**Comment by samreid** [comment]
Thanks, I added the dog and dollar and opened separate issues for the points you raised above.
