### ISSUE TITLE
Add series ammeter

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#270]
The Java version had an inline ammeter, which looked like this:

![image](https://cloud.githubusercontent.com/assets/679486/23727304/c08a03ba-0414-11e7-9ab9-04764da4da5a.png)

The HTML5 mockup shows one like this:

![image](https://cloud.githubusercontent.com/assets/679486/23727323/d370232e-0414-11e7-9961-abe93e6678af.png)

and it is in the sensor panel.

@arouinfar are you sure the HTML5 DC CCK needs an inline ammeter?  What if we just add an option under "values" to show readouts of currents through each element? That seems easier to program and simpler for students to use.

The current is already displayed through the electrons or conventional current (for direction and qualitative speed), and through the non contact ammeter for quantitative speed.

**Comment by arouinfar** [comment]
@samreid I think we're going to need the inline ammeter. There's been a lot of teacher pushback when it comes to the non-contact ammeter because it's different from how you would measure the current with a multi-meter. I think it's important to some teachers that students build and test circuits like they would in a real-world lab, which necessitates an inline ammeter.

That said, I like your suggestion to show the current through each element when Values in on. I wonder if we'll want to include current in the "Values" or if we'd want a separate checkbox for it, though.

I've started designing the inline-ammeter, based on the non-contact ammeter. I've created this preliminary design (with transparent windows to show the electrons), but I'm not that happy with it.
![image](https://cloud.githubusercontent.com/assets/8419308/23727477/743fd678-0415-11e7-91d8-fa9311774a8c.png)

It feels a bit too heavy and meter-y. We'll probably also want to allow for multiple inline ammeters, as we do in Java, so I think we'll need to lighten up the design a bit.

**Comment by samreid** [comment]
> with transparent windows to show the electrons

The electrons are "in front" of all the other circuit elements.  Why not have them be in front of the ammeter as well?

> There's been a lot of teacher pushback when it comes to the non-contact ammeter because it's different from how you would measure the current with a multi-meter

Should we discuss making one that looks like a real multi-meter?

**Comment by arouinfar** [comment]
> Why not have them be in front of the ammeter as well?

I think we'd want to create the illusion that the electrons are flowing through the inline ammeter, not on top of it.


> Should we discuss making one that looks like a real multi-meter?

Are you referring to an inline ammeter that would look something like this?
<img src="https://cloud.githubusercontent.com/assets/8419308/23730190/75a0b380-0423-11e7-9ed6-66252c955f86.png" width=200>

**Comment by samreid** [comment]
> I think we'd want to create the illusion that the electrons are flowing through the inline ammeter, not on top of it.

Yes, I agree that sounds important, but it also seems important to indicate that the electrons are flowing through the resistor, not on top of it.

> Are you referring to an inline ammeter that would look something like this?

Yes, that seems the best way to address teachers' concerns by drawing parallels with real multi-meters.

**Comment by arouinfar** [comment]
> Yes, I agree that sounds important, but it also seems important to indicate that the electrons are flowing through the resistor, not on top of it.

Touché. 😄 

> Yes, that seems the best way to address teachers' concerns by drawing parallels with real multi-meters.

We could consider this option, though I think we would need to show the electrons flowing through the probes/wires which seems a bit complicated.

**Comment by arouinfar** [comment]
Discussion of the inline ammeter is mostly in the [4/27](https://docs.google.com/document/d/1l9ABgqq4zgsU0f3nW4naylJ9fXGkX4RhBcLNrg0lsLE/edit#heading=h.5vakygffkqb), [5/4](https://docs.google.com/document/d/1l9ABgqq4zgsU0f3nW4naylJ9fXGkX4RhBcLNrg0lsLE/edit#heading=h.fra8bbmxvw0o), and [5/11](https://docs.google.com/document/d/1l9ABgqq4zgsU0f3nW4naylJ9fXGkX4RhBcLNrg0lsLE/edit#heading=h.xzy9uukwh9fl) meeting notes, but here are the major points:
* Lab screen only
* Inline ammeter will live in the toolbox (not carousel with other components)
* Toolbox will contain multiple (exact number TBD) inline ammeters
* Appearance will be tool-like (rather than wire-like)
* Electrons should appear to flow through it, so asset will have two layers.

I've cleaned up the design we discussed at last week's meeting. @ariel-phet has given this the 👍 so I'll go ahead and send the assets off to @samreid.

![image](https://cloud.githubusercontent.com/assets/8419308/26128689/84a67678-3a4a-11e7-852b-c8cf6f8d88c9.png)

**Comment by samreid** [comment]
The shading on this is very slight and I'll need regions to get the 3d clipping effect, so I'm tempted to draw this in code.

**Comment by samreid** [comment]
@arouinfar will the series ammeter change its appearance in schematic mode?

**Comment by arouinfar** [comment]
> @arouinfar will the series ammeter change its appearance in schematic mode?

Good question @samreid. I don't think any of the meters should change in schematic mode.

> The shading on this is very slight and I'll need regions to get the 3d clipping effect, so I'm tempted to draw this in code.

Sounds good! The shading doesn't need to exactly match the mockups so long as it's form a light source in the upper-left corner.

**Comment by samreid** [comment]
Good plan, thanks @arouinfar

**Comment by samreid** [comment]
The first draft is nearly complete. However, right now you can only "put back" series ammeters by putting them in the circuit element toolbox.  I need to change it so they get put back in the sensor toolbox instead.

**Comment by samreid** [comment]
I published a dev version here with the series ammeter:
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.22/circuit-construction-kit-dc_en.html

I already noted #324 about one issue.  @arouinfar can you test it out and provide feedback?

**Comment by arouinfar** [comment]
@samreid the series ammeter looks great! Functionally, everything seems good. I would recommend reducing the corner radius on the rounded rectangles a bit -- it feels too round. The mockups had a corner radius of 3pt. 

We should also discuss how many series ammeters to include in the toolbox. @samreid can you think of a disadvantage to increasing the number of ammeters to 5-8? Not sure if there would be a pedagogical advantage to having more, but it would be good to know if there would be programmatic issues (performance, or otherwise) with adding more.

**Comment by samreid** [comment]
It's easy to add more, but at some point when the number of circuit elements (of any type) gets too high, the sim will lag.  We'll reduce the rounding of the corners and go to 6 ammeters (unless you recommend another number).

@Denz1994 can you please take care of this?

**Comment by arouinfar** [comment]
Sounds good @samreid. I'll tag this for design meeting to discuss the desired number of series ammeters.

**Comment by Denz1994** [comment]
![image](https://cloud.githubusercontent.com/assets/13894380/26604401/809ab4d8-4547-11e7-880a-17569c36fa30.png)

The corners of the series ammeter were reduced as suggested and the black border was made a point slimmer. Does this seem okay @arouinfar? Please check dev version: http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.47/circuit-construction-kit-dc_en.html for review.

**Comment by arouinfar** [comment]
Looks good @Denz1994!

**Comment by arouinfar** [comment]
@samreid @Denz1994 is it possible that the series ammeter has been given some internal resistance? The battery doesn't have any internal resistance, yet the circuit on the left is registering 0.9 amps.

![image](https://cloud.githubusercontent.com/assets/8419308/26654651/d7d5166c-4614-11e7-9b99-b69a239957f6.png)

**Comment by samreid** [comment]
Good catch on the resistance, should be fixed in this version:
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.48/circuit-construction-kit-dc_en.html

Please verify.

**Comment by arouinfar** [comment]
Looks good @samreid!

**Comment by samreid** [comment]
Thanks, closing.
