### ISSUE TITLE
Solution for ideal wires

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#284]
After @Denz1994 and I discussed the wire situation in #282 I identified a potential strategy for solving circuits with 0-resistance loops.

Add another step to the solver that detects loops with 0 resistance.  If the voltage is zero, set the current of one of the elements in the loop to be 0.  If the net voltage is positive, set the current to be positive infinity.  If the net voltage is negative, set the current to be negative infinity.

On second thought, the QR decomposition may not handle infinities properly (though it may), but we could substitute a large positive or negative number and see if that works OK.  We would also want to handle infinities in the rest of the system (like animation speed).

In Java we wanted to support ideal wires because they are most similar to what students see in textbooks.  I did not have a solution like the one proposed above, so we went with the workaround of giving all wires a minimum of 1E-8 Ohms which seemed like it helped without causing too much complexity, though it still leads to corner cases like https://github.com/phetsims/circuit-construction-kit-common/issues/266

@kathy-phet @ariel-phet and @arouinfar do you think we should investigate this strategy for ideal wires?

**Comment by kathy-phet** [comment]
I don't think we should have ideal wires.
K

Sent from my iPhone

On Apr 13, 2017, at 8:34 PM, Sam Reid <notifications@github.com<mailto:notifications@github.com>> wrote:


After @Denz1994<https://github.com/Denz1994> and I discussed the wire situation in #282<https://github.com/phetsims/circuit-construction-kit-common/issues/282> I identified a potential strategy for solving circuits with 0-resistance loops.

Add another step to the solver that detects loops with 0 resistance. If the voltage is zero, set the current of one of the elements in the loop to be 0. If the net voltage is positive, set the current to be positive infinity. If the net voltage is negative, set the current to be negative infinity.

On second thought, the QR decomposition may not handle infinities properly (though it may), but we could substitute a large positive or negative number and see if that works OK. We would also want to handle infinities in the rest of the system (like animation speed).

In Java we wanted to support ideal wires because they are most similar to what students see in textbooks. I did not have a solution like the one proposed above, so we went with the workaround of giving all wires a minimum of 1E-8 Ohms which seemed like it helped without causing too much complexity, though it still leads to corner cases like #266<https://github.com/phetsims/circuit-construction-kit-common/issues/266>

@kathy-phet<https://github.com/kathy-phet> @ariel-phet<https://github.com/ariel-phet> and @arouinfar<https://github.com/arouinfar> do you think we should investigate this strategy for ideal wires?

**Comment by ariel-phet** [comment]
@samreid lets mark priority deferred (I do not agree with @kathy-phet - since many teachers would find it a useful feature to model ideal wires), but I definitely do not think we need to investigate for initial publication.

**Comment by arouinfar** [comment]
I agree with @ariel-phet -- no need to include ideal wires in 1.0.  I think this is a feature that some teachers would be interested in using, and we could consider it for a later version.

**Comment by samreid** [comment]
This does not seem in the scope for AC publication, so I've re-deferred.

**Comment by arouinfar** [comment]
@samreid as far as I know, there haven't been any requests for ideal wires.

**Comment by samreid** [comment]
At today's design meeting, we discussed https://github.com/phetsims/circuit-construction-kit-common/issues/677 and https://github.com/phetsims/circuit-construction-kit-common/issues/676 and would like to investigate a model solution that supports ideal wires.  My estimate was:

I think it could take half a day to know if it will work.  If it does work, then it would probably be a couple of days to get everything working.

To clarify, this is 4 hours or so to test it out.  Then 16 hours to get it working.  This is all +/- a standard deviation or two.

**Comment by samreid** [comment]
Here's a simple circuit that demonstrate the problem.  From the published version of DC virtual lab:

![image](https://user-images.githubusercontent.com/679486/110520957-60c2e080-80cc-11eb-8bf9-e3fb96c166e3.png)

If I change wires to be implemented as 0 voltage batteries, then most of the infrastructure we need is already there, and basic things are working nicely.

![image](https://user-images.githubusercontent.com/679486/110521174-a5e71280-80cc-11eb-89fd-ed6127d521c9.png)

I think I'll commit this progress so far, but we will need to discuss the other places that `MINIMUM_RESISTANCE` is in play.  Currently the default battery resistance is `1E-8` (the former minimum value for wire resistance).  Should we allow it to go to 0 as well?  Same question for fuses.  If I naively set `MINIMUM_RESISTANCE=0` then I see the buggy behavior of battery+wires (no resistors) not causing any current.  I presume there is some infinity or equivalent in the linear algebra, but I didn't want to spend more time on that without checking if we want ideal batteries (and fuses) as well as ideal resistors.

**Comment by samreid** [comment]
I committed an initial draft of ideal wires.  @arouinfar can you please review and comment on whether we also would like to investigate ideal batteries and/or fuses?

**Comment by samreid** [comment]
@arouinfar pointed out that a wires-only circuit breaks other circuits:

![image](https://user-images.githubusercontent.com/679486/110852725-f2b71e80-826f-11eb-89ac-eabe67fc2641.png)

**Comment by samreid** [comment]
Today we looked at cases like the above and cases like this one.

![image](https://user-images.githubusercontent.com/679486/110857442-17ae9000-8276-11eb-8ca4-b055e1a2727d.png)

This is unsolvable for ideal wires because electrons could go around the loop an arbitrary (even infinite) number of times.

We will revert the "add support for ideal wires" commit.  After that is reverted, we will make sure the commit from https://github.com/phetsims/circuit-construction-kit-common/issues/676 is in master, and @kathy-phet will take a look.

@arouinfar will update the documentation accordingly.

**Comment by samreid** [comment]
Brainstorming another idea:

What if we add 2 "ideal wires" to each screen (in the carousel)?  We can depict them differently than normal wires.  Their existence will draw attention to the fact that the other wires are non-ideal.  Then the user can use the 2 ideal wires to make circuits like this mindfully:
![image](https://user-images.githubusercontent.com/679486/110858282-1df13c00-8277-11eb-80dd-5bf1bb196e97.png)


2 ideal wires is enough to get to learning goals like this, but not enough to create a loop anywhere.  What do you think @arouinfar and @kathy-phet?

**Comment by samreid** [comment]
I reverted the "add ideal wires" commit, haven't had a chance to sanity test it though.

**Comment by samreid** [comment]
Also, I don't recall the numerical errors, but what if we put batteries at 1E-10 ohms and wires at 1E-20 ohms?  Would that give the results we expect in cases like https://github.com/phetsims/circuit-construction-kit-common/issues/284#issuecomment-794297660 ?

**Comment by samreid** [comment]
The solution in https://github.com/phetsims/circuit-construction-kit-common/issues/676 seems superior to any alternative proposed in this issue, closing.
