### ISSUE TITLE
Default schematic battery obscured by electron

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#285]
If you get a battery then click schematic, you will see this:

![image](https://cloud.githubusercontent.com/assets/679486/25098171/c3856356-2364-11e7-96bf-52d8c8dce55c.png)

It looks odd because the electron spans the gap in the battery.  If "show electrons" is on by default, it seems like we should do something about this.  It is not as much of a problem once the electrons are moving.

**Comment by arouinfar** [comment]
@samreid I'm not sure that this is a problem, as the gap between the vertical lines isn't a physical break in the circuit (as an open switch would be). 

I'm also not particularly bothered by this because the schematic view is not the default. We don't know when/if a user will trigger that scene, or if they will still have the electrons turned on. However, the user will always be able to see the unobscured schematic battery in the toolbox, or turn electrons off.  

@samreid have you thought about alternatives? I can think of a simple alternative -- move the vertical lines slightly off-center. Frankly, I think this will look slightly odd, but the default position of the electrons wouldn't obscure the gap.

**Comment by samreid** [comment]
Not sure what's best, but I'll brainstorm some possibilities:

(a) leave it as it is
(b) make the electrons partially transparent
(c) add a clipping region so nothing is rendered between the plates.
(d) change the default density or battery metrics so that there are 4 electrons in the battery and nothing starts in the middle.

**Comment by arouinfar** [comment]
@samreid thanks for brainstorming some options. I like option (b), as I sometimes find myself turning off the electrons because they get in the way. A slight reduction in opacity would alleviate the issue. We can discuss these options further in design meeting.

**Comment by arouinfar** [comment]
Opacity of electrons and current arrows has been reduced to 75%. 

Reviewed in design meeting, and we love the look of the transparent electrons. They look more ethereal. @samreid we'll need  to see what effects this has on performance though.

**Comment by samreid** [comment]
Testing performance in https://github.com/phetsims/circuit-construction-kit-common/issues/293
