### ISSUE TITLE
Ohms vs Ω

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#304]
Discovered during #289.  The readouts are showing a Ω but the edit panel shows a "Ohms".  Should these be intentionally different so students may put it together that Ω means ohms?  Or should they be the same so the sim is consistent?

![image](https://cloud.githubusercontent.com/assets/679486/25769818/f5baf7b6-31e0-11e7-8a8c-2b5840bd7141.png)

**Comment by arouinfar** [comment]
@samreid great question. Do you remember any discussion around abbreviations vs. spelled out units in the original design? 

I would prefer to use abbreviated units in Show Values to save space in the play area. It would be nice to keep the unit spelled out in the edit panel, particularly because of the younger audience that uses this sim. I don't see a problem with requiring users to coordinate V/volts or Ω/ohms, as this is something that happens all the time in the classroom.

**Comment by samreid** [comment]
Use "ohms" in the single occurrence panels.  Use "OHM symbol" in where it appears repeated over the circuit elements.

**Comment by samreid** [comment]
@arouinfar does this look OK in http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.20/circuit-construction-kit-dc_en.html

?

**Comment by arouinfar** [comment]
👍
