### ISSUE TITLE
Show part of the dotted line behind the component?

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#35]
I'm not sure if it is possible, but what if we could show the dotted line behind the image, so it is not obscured?  Picking would work the same way it does now.

Current behavior:
![image](https://cloud.githubusercontent.com/assets/679486/14062439/4f97b880-f364-11e5-97fa-9e865fae436a.png)

Requested behavior:
![image](https://cloud.githubusercontent.com/assets/679486/14062446/8502d8c4-f364-11e5-8c60-5f9219d7b9a0.png)

Part of the trick is that pickability should still work the same (invisible vertex node in front), so that two batteries next to each other can still have the vertex selected.

**Comment by samreid** [comment]
This request is to make the battery image look clearer, so it is not obscured by dotted lines which could be confusing to students.

**Comment by samreid** [comment]
Tagging @ariel-phet and @arouinfar in case they have thoughts about this idea.

**Comment by samreid** [comment]
I don't recall this being an issue in the Java version, so let's discuss this before spending time on it.  @arouinfar can you comment?

**Comment by arouinfar** [comment]
In the Java version of CCK, the dotted lines are always layered above all circuit components. I've noticed that it's a bit more variable in master. When resistors and bulbs are dragged out of the toolbox the dotted lines are layered behind the component, but once a node is connected, the dotted line pops to the front. In Java (and the mockups) disconnected nodes are red, while those that are connected to at least one component are black. This feature is currently missing from master, but it is one that Stanford would like in the MVP. While it's clearly not a top priority, it seems like an easier change.

![image](https://cloud.githubusercontent.com/assets/8419308/14150534/b9ce635c-f666-11e5-9692-03b224aecc02.png)

@samreid the dotted line cues that the node is clickable. I think it's important that the dotted lines are layered above the nodes when they are connected, otherwise they will get lost in the background. I wouldn't mind if the the dotted lines are initially layered behind disconnected nodes (like the bulb and battery in the screenshot above), so long as all components behave the same way. I'm not sure if it will feel inconsistent if disconnected nodes are layered behind the component, but connected ones are layered above. 

We can discuss this issue at the next design meeting.

**Comment by samreid** [comment]
I temporarily assigned to me with the idea to create issues for the preceding comment, but on second thought waiting until design meeting sounds good.

**Comment by samreid** [comment]
> I'm not sure if it will feel inconsistent if disconnected nodes are layered behind the component, but connected ones are layered above.

It does seem unnecessarily complex for disconnected vertices to be behind and connected vertices to be in front, so I'll close this issue and open a separate issue for the remaining issue of:

> In Java (and the mockups) disconnected nodes are red, while those that are connected to at least one component are black. This feature is currently missing from master, but it is one that Stanford would like in the MVP.
