### ISSUE TITLE
Paper clip electron placement looks odd

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#353]
When I added the paperclip graphic, it looked like this:
![image](https://cloud.githubusercontent.com/assets/679486/26739784/6c101a94-4790-11e7-98c3-96077000233d.png)

It seemed odd to me that the electrons are in the blank space of the paperclip.  Should we address this, and if so, how?

**Comment by arouinfar** [comment]
Good catch @samreid. I reviewed master, and the paper clip seems a bit large. Can you scale it down so it's the same length as the battery? I've also lengthened  the interior curve so that the electrons are always in contact with the paper clip, and have emailed you the updated assets.

![image](https://cloud.githubusercontent.com/assets/8419308/26743348/b252a5cc-479e-11e7-9829-fc13818fc110.png)

**Comment by samreid** [comment]
This cannot be implemented until https://github.com/phetsims/circuit-construction-kit-common/issues/354 is complete.

**Comment by samreid** [comment]
The size was adjusted in https://github.com/phetsims/circuit-construction-kit-common/issues/363

Latest dev version is here:
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.62/circuit-construction-kit-dc_en.html

@arouinfar can you see if everything is OK?

**Comment by arouinfar** [comment]
👍
