### ISSUE TITLE
Wonky wire ends on iPad

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-common#390]
Observed in dev.91 for https://github.com/phetsims/QA/issues/26 on iPad 2 and iPad Air. Possibly related to https://github.com/phetsims/circuit-construction-kit-dc/issues/78. 

The ends of the wire in the toolbox look a bit misaligned/too large, but appear normal in the play area. 
![fullsizerender](https://user-images.githubusercontent.com/8419308/28474508-3bc5ff24-6e06-11e7-86c0-5872063a38e8.jpg)

This is NOT important for AAPT.

**Comment by samreid** [comment]
I'm seeing the same wonkiness on my iPad2.

**Comment by samreid** [comment]
When I scale the toolbox node up to a factor of 4, the wire icon looks OK on iPad2.  @jonathanolson can you help on this issue?  I'm not sure where to look next.

**Comment by samreid** [comment]
Workaround seems OK to me, not sure if I should close it or discuss with @jonathanolson.  I'll leave it up to him!

**Comment by samreid** [comment]
Oops, workaround doesn't switch to schematic.

**Comment by samreid** [comment]
It would be easy to take the workaround to the next level and rasterize schematic and lifelike icons, but that would make it more difficult for @jonathanolson to reproduce the problem, so I'll wait on that.  Instead, I'll roll back the initial workaround so @jonathanolson can easily see the problem.

**Comment by samreid** [comment]
OK we're back where we started.  @jonathanolson can we schedule a time to investigate?

**Comment by samreid** [comment]
In the preceding commit, @jonathanolson and I added padding to the wire caps and things are looking better on iPad2 (no more drooping down) though not perfectly vertically symmetrical (peak is about 2/3 of the way down instead of 1/2 way down).  On iPad3 it seems perfectly symmetrical now.  @jonathanolson and I discussed workarounds for avoiding this, but they would lead to a divergence of code and we are wondering if this solution is "good enough".  @arouinfar can you please test on an iPad2?  (I couldn't find an easy way to share images off of the PhET iPad2).

http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.103/circuit-construction-kit-dc_en.html

**Comment by samreid** [comment]
We couldn't find a way to share images from Witten, so here's a snap from my phone:

![image](https://user-images.githubusercontent.com/679486/28584997-0bcacc22-712c-11e7-8a56-97131a528678.png)

We are concerned that the alignment is good on every other platform and if we make an iPad2 specific fix here, it will be broken if/when mobile safari gets fixed.

We could create a separate renderer for the icon in 30-60 minutes--but wanted to check if this is good enough.

**Comment by arouinfar** [comment]
@samreid I reviewed dev.103 on the iPad2, and the wire looks great. I don't think you need to worry about doing anything else.

By the way, you should be able to use AirDrop to transfer screenshots from the iPad2 to your Mac.
