### ISSUE TITLE
Items for Teacher tips

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/circuit-construction-kit-common#411]
I am sure there is lots for this one @arouinfar, i will get it started with a few, definitely add on :)

- [ ] Both the electrons and conventional current representations are "cartoon" representations and do not perfectly model the current in the circuit. Their speed and density give an approximate visual but should not be taken literally. 
- [ ] Some comment about where the sim tends to have instability
- [ ] A comment about the noncontact ammeter and how such devices do exist

**Comment by phet-steele** [comment]
@ariel-phet should this belong in the CCKDC repo? Since..this isn't a sim repo? Or did you want this to be some sort of "broad teacher tips" issue for the CCK suite? If it's the prior case, there exists a teacher tips issue for CCKDC here: https://github.com/phetsims/circuit-construction-kit-dc/issues/41

**Comment by ariel-phet** [comment]
Good call @phet-steele I was just looking at issues in this repo and forgot where I was!
