### ISSUE TITLE
Label name for "AC Source"

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#453]
The design doc shows the label name for the oscillating source as "AC Source", which expands to "Alternating Current Source".  I'm wondering if some clients may misconstrue this as a type of "current source" https://en.wikipedia.org/wiki/Current_source as opposed to a voltage source, which is how we have been modeling it.  Should this be named something else?

**Comment by samreid** [comment]
I noted in Java this was called "AC Voltage":

![image](https://user-images.githubusercontent.com/679486/52920529-805ef480-32ca-11e9-95ad-77a68de58324.png)

**Comment by arouinfar** [comment]
@samreid you make a good point. I can see how "AC Source" could be interpreted as a current source. After all, its name is alternating current source, which is ambiguous at best. I think "AC Voltage" would probably be a better name for both the circuit component and first screen. 

Any objections @ariel-phet?

**Comment by ariel-phet** [comment]
No objections. The symbol we are using on the item matches up with the international "AC voltage source".

If we needed some brevity we could call this "AC Supply" or even simply "AC"....It is not like we call the battery a "DC voltage source" even though that that is what it is.

I think the screen name can still be "AC" - yes we have AC Voltage sources, but in the circuit those induce Alternating Current, and since electrons are illustrated as sloshing back and forth, I think I would just leave the name of the screen as AC, since that is also how we talk about things when teaching "AC circuits".

**Comment by arouinfar** [comment]
Thanks @ariel-phet.

Let's proceed with calling the circuit component  and first screen "AC Voltage". This naming aligns with Java. I don't think "AC Voltage" is too verbose for a screen name, and is more descriptive than simply "AC".

**Comment by samreid** [comment]
It's renamed to "AC Voltage", @arouinfar do you mind double checking that everything seems ok?  You can't see the screen name for AC CCK yet because it only has one screen so far.  Close if all is well.

**Comment by arouinfar** [comment]
:+1:
