### ISSUE TITLE
What should be shown for the fuse when "Values" is checked, if anything?

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#464]
Should anything be shown for the fuse when "Values" is checked?  Brainstorming some possibilities:

* Don't show anything for "values"
* Show the text "tripped" or "not tripped"
* Show the percentage of current to maxCurrent--the way to being tripped, example: "75%"
* Show the current value and the max current: example: 3.0 A / 5.0 A

Until we decide on this, the simplest implementation is to show its resistance as "0" or "NaN" ohms.

**Comment by arouinfar** [comment]
@samreid @kathy-phet I think the most useful information to show would be the current rating, otherwise users would need to open the edit panel to see this information.  That said, I'm a bit apprehensive about showing just the current rating because I wonder if it could be interpreted as the actual current through the component. I'm leaning towards something like `3.0 A / 5.0 A`.

I don't think "tripped" or "not tripped" is particularly useful, since that would be clear from the component itself, as well as the behavior of the circuit. A percentage might also not be that clear to users, especially those unfamiliar with fuses.

**Comment by samreid** [comment]
I implemented like `3.0 A / 5.0 A` and it can be seen in phettest.  It seems nice to me.

**Comment by arouinfar** [comment]
Looks good in master @samreid. Tagging for design meeting for review with @kathy-phet and @ariel-phet.

**Comment by arouinfar** [comment]
Discussed this with @ariel-phet in today's brainstorming meeting.

Fuses generally have internal resistance, so that seems like the most appropriate value to display (and a nice parallel to the switch). However, the model of the fuse doesn't currently include any internal resistance, see #480. 

Marking this issue as on-hold until #480 is discussed/addressed.

**Comment by arouinfar** [comment]
Tagging https://github.com/phetsims/circuit-construction-kit-common/issues/463

**Comment by arouinfar** [comment]
This was handled in #463, so closing.
