### ISSUE TITLE
Include internal resistance in fuse model?

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-common#480]
Related to #463.

From https://en.wikipedia.org/wiki/Fuse_(electrical)#Construction
> The resistance of the element generates heat due to the current flow... If too high a current flows, the element rises to a higher temperature and either directly melts, or else melts a soldered joint within the fuse, opening the circuit.

In reality, a fuse would have internal resistance. The lower the tolerance, the higher the resistance. Here's some [empirical data](https://w220.ee/DIY_Voltage_Drop_Across_Fuses_-_Quiescent_Current_or_Parasitic_Discharge_Tests) for the relationship between the current rating and the internal resistance.

<img src="https://user-images.githubusercontent.com/8419308/55841375-26b9c000-5aec-11e9-96a7-a508e53eec64.png" width=200>

For this data set, current rating appears to be proportional to 1/R
![image](https://user-images.githubusercontent.com/8419308/55841918-8618cf80-5aee-11e9-93b4-4afd9f87c27b.png)

The current model of the fuse does not include any internal resistance, which may get some pushback. An alternative would be to map the current rating to an internal resistance. Using the above data as a stand-in, we could map a current rating of 20.0 A to 3 mΩ, with the current rating proportional to 1/R.

@samreid can you give an estimate of how much time it might take to change the model of the fuse? Tagging for design meeting for further discussion with @ariel-phet and @kathy-phet.

**Comment by samreid** [comment]
In order to understand how the change in resistance will appear in the user experience, I computed the current for a 9V battery and 10 Ohm resistor (the defaults), with 10 Amp and 20 Amp rated fuses in series.

```
I = V/R
I = 9/(R+x)
at 10 A rating: I = 9/(10 + 7.4E-3) = 9/10.0074 = 0.89933 A
at 20 A rating: I = 9/(10 + 3.0E-3) = 9/10.0030 = 0.89973 A
```
However, the ammeter only reads out to 2 decimal places.  So I'm curious about the motivation for this issue, and what learning goals we are trying to address.  Is it about seeing the electrons move a bit slower?  Seeing different readings in the ammeters?  Splitting up the voltage drop?  Some possibilities for brainstorming/discussion: (a) increase the fuse resistance so it has more of an effect (b) increase the resolution of the ammeters (c) treat this as an ideal (resistance-less) fuse.

**Comment by samreid** [comment]
@ariel-phet and @kathy-phet and I discussed this, and we would like to add resistance to the fuses.  We will use values like the ones in the given table.  So the default would have some round number.

Instead of reading "1.2 A / 4.0 A", we will change that to read: "max 4.0 A".
@ariel-phet wants to show the resistance in the "show values"

@kathy-phet said the primary learning goal is about the fuse tripping at a certain amperage.  But that if we use the resistances that are listed, it could address how the fuse trips, so it won't impact the numbers too much.  It will look ideal.

@ariel-phet says we could show values: "20 mΩ (4 A)".
@kathy-phet: we could try that, we'll have to see how students interpret it.  It could work.
@ariel-phet: this is preferable because it indicates the fuse to be a resistive element.

**Comment by samreid** [comment]
We will have to be cautious about a re-entrant property loop of the following form:

1. Current rating changes
2. Resistance changes
3. Current changes
4. Fuse is tripped
5. Resistance changes

Since changing the resistance can cause a re-entrant change to itself, I'm inclined to move the resistance change step to the model.step function so it won't create a loop.

**Comment by samreid** [comment]
The commit computes resistance during the step() function using `resistance = 0.06 / currentRating`, which has 3 mΩ at 20.0 A as recommended in the 2nd to last paragraph of https://github.com/phetsims/circuit-construction-kit-common/issues/480#issue-431244202.

With a default battery, default resistor, tuning the fuse to 1.0 A rating drops the current displayed in the ammeter from 0.9 A to 0.89 A.

I'll continue working on this pattern for display values: "20 mΩ (4 A)".

**Comment by samreid** [comment]
This commit updates the value pattern, the default value is nice and round:

![image](https://user-images.githubusercontent.com/679486/56179276-39d40080-5fc2-11e9-81c6-2f21c2ee7256.png)

@arouinfar and @ariel-phet please test/review/feedback.

**Comment by ariel-phet** [comment]
@samreid When the fuse breaks, it is reading some larger number of mOhms, can we just change that to read infinity just like the switch once we go above a certain threshold?

I know the parentheses was my idea, not sure I love it, curious what @arouinfar thinks. Maybe if we wrote the amperage in more of a gray than black text it would feel less like it was reading out the current and more "label-esque"

**Comment by kathy-phet** [comment]
for the reading, would <4.0 A (or less than or equal to sign) be a bit clearer that it is a limit?

**Comment by samreid** [comment]
The commit shows `∞ mΩ` when the fuse is tripped.  I also considered showing `∞ Ω`, but it seemed odd to switch units and the code already supported `mΩ` without additional work.  But let me know if you want to go for `∞ Ω` instead.

Showing `<4.0 A` adjacent to the other reading could look like an expression: `10 mΩ <4.0 A` could be misread as "10 milliOhms is less than 4 Amps".

I also considered removing the current rating readout from the fuse, thinking that you could always click on the fuse to see the rating.  But the problem with that idea is: the user will be manipulating the characteristics of another component (say, increasing the voltage of a battery) and could use an ammeter to read out the current, and it is nice to also see the current rating at the same time.

Anyways, I'll wait for further discussion before working further on this issue.

**Comment by arouinfar** [comment]
> The commit computes resistance during the step() function using resistance = 0.06 / currentRating, which has 3 mΩ at 20.0 A

@samreid this is looking great!

> I know the parentheses was my idea, not sure I love it, curious what @arouinfar thinks. Maybe if we wrote the amperage in more of a gray than black text it would feel less like it was reading out the current and more "label-esque"

Thanks for the suggestion @ariel-phet. I do agree that the `(4.0 A)` leave something to be desired. I'm not sure that the text color would be enough of an indicator that it's a label, not the actual current reading. @samreid and @kathy-phet had some other suggestions I'd like to try out.

> for the reading, would <4.0 A (or less than or equal to sign) be a bit clearer that it is a limit?

I like this idea @kathy-phet! 

> The commit shows ∞ mΩ when the fuse is tripped. I also considered showing ∞ Ω, but it seemed odd to switch units and the code already supported mΩ without additional work.

Let's leave it `mΩ` @samreid. I don't think we need to change the unit for the label to be appropriately interpreted.

> But the problem with that idea is: the user will be manipulating the characteristics of another component (say, increasing the voltage of a battery) and could use an ammeter to read out the current, and it is nice to also see the current rating at the same time.

Agreed. This is exactly why I'd like to see the current rating in the label.

> Another possibility we haven't discussed yet would be to put them on separate lines, which also buys us horizontal space. I don't love this idea, just brainstorming it.

My initial thought was to split the label onto two lines, as we do when batteries have internal resistance, so glad to see this suggestion from you.
![image](https://user-images.githubusercontent.com/8419308/56227443-ba324a00-6032-11e9-98dc-4ec9c69b2a4e.png)

I think we could try either of these options. For i18n, I think `≤ 4.0 A` may be preferable to `max 4.0 A`.

```
15.0 mΩ
≤ 4.0 A
```

```
15.0 mΩ
max 4.0 A
```

**Comment by samreid** [comment]
I've moved the current rating down a line, @arouinfar can you please review?

**Comment by arouinfar** [comment]
I like it! Thanks @samreid.

Any thoughts on the fuse label @ariel-phet @kathy-phet?
![image](https://user-images.githubusercontent.com/8419308/56550352-a4e18200-6542-11e9-86d4-640c0754340a.png)

**Comment by ariel-phet** [comment]
@arouinfar working nicely for me. I might consider bumping down the font size of the current rating, but I think having it on a separate line with the "less than or equal" to symbol works very nicely.

I think having them be different fonts may make these two values feel more different, but it probably will work just fine as is.

**Comment by arouinfar** [comment]
> I might consider bumping down the font size of the current rating, but I think having it on a separate line with the "less than or equal" to symbol works very nicely.

Nice idea @ariel-phet! @samreid is this something you can try out?

**Comment by samreid** [comment]
Recording some options as I go:

font-size: 14px;

![image](https://user-images.githubusercontent.com/679486/56969592-b6b6bc80-6b22-11e9-981d-3e9815936b55.png)

font size 18

![image](https://user-images.githubusercontent.com/679486/56969622-c6360580-6b22-11e9-863c-6111936d922d.png)

Italics:
![image](https://user-images.githubusercontent.com/679486/56969672-e796f180-6b22-11e9-85e8-808db841acf0.png)

font size 16

![image](https://user-images.githubusercontent.com/679486/56969758-0e552800-6b23-11e9-8b76-c7c78828886b.png)

I'm inclined to go with font size 18, because it is different enough than the main font, but large enough to see from the back of the classroom.

**Comment by samreid** [comment]
Pushed, @arouinfar and @ariel-phet can you please review on phettest and provide feedback?

**Comment by arouinfar** [comment]
Thanks @samreid. I'm leaning more towards the 16 pt option (still very readable, but less emphasized), but would be completely fine with 18 pt if that's what others prefer.

After playing a bit on master, I think we might want to instead right-align the strings so the units are at least somewhat aligned. That would also be more consistent with the battery label when there's internal resistance.

![image](https://user-images.githubusercontent.com/8419308/56977339-2e401800-6b32-11e9-91fc-c6024cdaa3bb.png)

![image](https://user-images.githubusercontent.com/8419308/56978372-8bd56400-6b34-11e9-8aba-c6ce02d7bcde.png)

**Comment by ariel-phet** [comment]
Agreed with @arouinfar comments above, right aligned, 16 pt font

**Comment by samreid** [comment]
I pushed 16 point font and right aligned text, it looks like this:

![image](https://user-images.githubusercontent.com/679486/57090786-d2f25f00-6cc4-11e9-8f51-94b99079093d.png)

@arouinfar or @ariel-phet anything else for this issue?

**Comment by arouinfar** [comment]
Looks good to me @samreid!

**Comment by ariel-phet** [comment]
Agreed, I think this is really nice. I know we played around with many solutions, but I think this works well. 

Closing

**Comment by KatieWoe** [comment]
Examining for https://github.com/phetsims/QA/issues/314 and I do have a suggestion/thought.  On the battery the Voltage is on top and resistance is on bottom.  I think that resistance should be on the bottom for the fuse as well.  Especially since the Amp rating has a larger effect on the circuit in pretty much all cases in the sim.  I'm also unsure why that text is smaller.

**Comment by ariel-phet** [comment]
@KatieWoe the choice to de-emphasize the current rating was very intentional, with lots of design discussion. You are correct that the current rating has a clear effect on the circuit. However, two important points:

1. The current rating (if prominent) might get confused with the actual current in the circuit. Especially if you are varying the current rating, it could easily be mistaken as a current readout, even if the actual current is not changing. For the battery the listed voltage is the voltage being output by the battery, but we don't want students to think the current rating is the current through the resistor.

2. The fuse is a resistive element. Basically all items in the sim are resistive elements or batteries. So it is natural to label the fuse with its resistance prominently. In fact, the resistance of the fuse is key for its ability to burn out.
