### ISSUE TITLE
User request: 2 or 3 significant figures

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/circuit-construction-kit-common#497]
> It would be better if the Circuit Construction Kit:DC -virtual lab always showed amps to 2 or 3 significant figures and/or have a milliampmeter. Showing only one sig fig for amps is a problem.

**Comment by samreid** [comment]
@arouinfar can you please recommend how to proceed?

**Comment by arouinfar** [comment]
Ammeters always show at least 2 decimal places, which increases to 3 when the current is below 0.02 amps.

The `1.00` reading has 3 sig figs, and the `0.017` reading has 2 sig figs.
<img src="https://user-images.githubusercontent.com/8419308/65708342-98aaa500-e04b-11e9-9c00-6a6add5802f9.png" width=200> <img src="https://user-images.githubusercontent.com/8419308/65708491-ef17e380-e04b-11e9-9f26-3e21332d97e0.png" width=200>

> Showing only one sig fig for amps is a problem.

I think the user is concerned when there truly is only ONE sig fig, such as these cases. 
<img src="https://user-images.githubusercontent.com/8419308/65708770-9268f880-e04c-11e9-8d81-df05899650bd.png" width=200> <img src="https://user-images.githubusercontent.com/8419308/65708894-cd6b2c00-e04c-11e9-8d61-c00fd5f301b7.png" width=200>

Frankly, I don't share the user's concerns. The one case that looks a bit weird to me is that currents below 0.001 amps display `0.00 A` but would better to be shown as `0.000 A`. However, in these examples I'm doing something that isn't particularly pedagogically valuable -- I'm mixing high-resistance resistors with low-voltage batteries. 
<img src="https://user-images.githubusercontent.com/8419308/65709442-12dc2900-e04e-11e9-8af8-5b7051372b95.png" width=200> <img src="https://user-images.githubusercontent.com/8419308/65709460-1ff91800-e04e-11e9-8242-09a53bb5f9b7.png" width=200>

@samreid would you be able to display `0.000 A` for non-zero currents that are less than 0.001 amps?

**Comment by samreid** [comment]
The existing implementation is:
if (value is between 0.001 and 0.02) => 3 decimal places
otherwise => 2 decimal places

Would it accomplish our goals to change it to:
if (value is above zero and below 0.02) => 3 decimal places
otherwise => 2 decimal places

Do we need to build in some slack, like making the lower threshold 1E-6 to handle approximate zeros?

For my future reference, the code is located here:
https://github.com/phetsims/circuit-construction-kit-common/blob/d85dd8d78aef48bd9d0ebc4635f99f7d2e4f0651/js/CCKCUtil.js#L22-L30

**Comment by arouinfar** [comment]
> Would it accomplish our goals to change it to:
if (value is above zero and below 0.02) => 3 decimal places
otherwise => 2 decimal places

@samreid yes, I think this would give us the desired result. Let's use this approach. 

> Do we need to build in some slack, like making the lower threshold 1E-6 to handle approximate zeros?

Let's see how things work out. If we're seeing odd behavior at low currents, we could try out a small, non-zero threshold instead.

**Comment by samreid** [comment]
The commit uses 3 decimal places for values less than 0.02. I tested the example in the bottom right of https://github.com/phetsims/circuit-construction-kit-common/issues/497#issuecomment-535601130 and the current is actually `0.0009499999578110875` which rounds to `0.001` instead of `0.000`.  @arouinfar can you please review?

**Comment by arouinfar** [comment]
@samreid this is looking good in master. Thanks!
