### ISSUE TITLE
Fuse can trip despite being within tolerance rating

### ISSUE THREAD

**Issue by Denz1994** [phetsims/circuit-construction-kit-common#498]
Found during the code review of the fuse node https://github.com/phetsims/circuit-construction-kit-common/issues/495.

_Circuit Setup (Lab Screen):_ 
- Set up a circuit with one battery (40.5 V), one resistor (10 ohms), a fuse (4.0 A), 2 wires, and an inline ammeter.
- Wire resistivity should only be slightly raised, so it isn't at the default (zero).

_Steps to reproduce:_
1. Set up the circuit as described above.
2. Adjust the circuit current to match the ammeter with the fuse rating (4.0A) by either:
       2a. Lengthening the wires so the circuit is longer/shorter
       2b. Slightly raising/lowering the wire resistivity
3. If the fuse breaks, reset the fuse and pay attention to the ammeter reading, it will flicker a quick reading before breaking again.
4. With enough minor adjustments (step 2-3), your fuse will trip and the ammeter would flicker with a reading within the tolerance rating.

It takes a few times to set up the circuit just right but isn't hard to do if your intention is to experiment with breaking the fuse right at its tolerance level. This may have to do with an inconsistency in how the ammeter reading is rounded compared to the tripping tolerance.

I brought this to @samreid attention and he stated the following:
> Not a strong opinion on this either way. I'm not exactly sure of the implementation of a solution. This may be more of a problem for younger audiences rather than older groups. I would get input from @arouinfar or @ariel-phet.

**Comment by Denz1994** [comment]
I would be happy to demonstrate over zoom if need be. I wasn't successful with getting a gif imported.

**Comment by phet-steele** [comment]
Was there ever a discussion about truncating the ammeter after two places so it says 3.99?

![image](https://user-images.githubusercontent.com/5863899/58126023-2c1c2700-7bcf-11e9-9760-7b830a612a3b.png)

**Comment by ariel-phet** [comment]
@Denz1994 I looked at this, and personally I think everything is fine. It is great attention to detail on your part, but I have not seen a circumstance that would cause me concern. We don't put a +/- percentage on the fuse, but a real fuse does have some variation, and the slight inconsistency that can be seen in tripping here does not raise any pedagogical flags for me. 

The fuse also says < or = to 4.0 A in this case, so from significant figures there is already an implication that the 100's digit is a bit uncertain. Still I have not seen a case where the fuse trips at 4.01 instead of 4.00

Again, the thoroughness is appreciated, but I think in this particular case everything is reasonable for the model we are using and the assumption that there is some slight variation in fuses. 

Closing.
