### ISSUE TITLE
User question: implementation of ammeters

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/circuit-construction-kit-common#508]
First, let me say I love your work!  

However, I think there may be something amiss with the ac circuit simulation's implementation of ammeters.  Admittedly, that something might be my interpretation, but I'd like to have someone look into this and either fix it or let me know what I'm doing incorrectly.

In the tools for teachers, there is a nice example of LR circuit behavior, which uses a battery driving two parallel branches of the circuit - one with only a lamp of 10 ohms, and the other with an identical lamp and a 10 henry inductor in series with the lamp.  When using the ammeter to measure the currents, I do get the proper values, and the "electrons" are moving in the correct directions.  When the switch is opened to disconnect the battery from the circuit, the currents decay appropriately.  However, the ammeters do not show that the current in the branch without the inductor reverses direction - they only measure magnitude (electron movement does reflect this change in direction.)  I tried using the current chart feature.  This does show the reversal of current, but seems to have the initial polarity wrong.  I thought perhaps the current chart was connected "backwards", but no polarity marks are shown. 

 The attached screenshot shows the current charts for each branch of a similar circuit (I used resistors rather than lamps); looking at the junction of the two resistor branches with the branch containing the battery, it appears that Kirchhoff's current law is violated: Current entering the node from the battery is 2 A, current leaving is +1 -1 =0 A.  

What did I miss?

 Thanks for your help, and keep up the good work!

![image](https://cloud.githubusercontent.com/assets/5090275/18886923/44813976-84af-11e6-99b6-0a1862f562ad.png)

**Comment by samreid** [comment]
Here's a proposal for one way that might address this.  The first time a circuit component gets a nonzero current, that determines the directionality for the component.  The directionality is chosen so that all initial currents are positive.  This way, when setting up an initial circuit, all currents will be consistently positive.  When the circuit element's current goes to zero (for instance, if it is detached), we clear its directionality.  This way, we can get replicable and consistent behavior for the signs of currents and still support positive and negative current.

I don't feel I have thought through all of the corner cases, but this seems good enough to bring up for discussion at design meeting.

**Comment by samreid** [comment]
We discussed this and could not think of better alternatives (unless there is some way to leverage the directionality of electrons), we would like to give this a try.

**Comment by samreid** [comment]
Proposed fix implemented, @arouinfar can you please review?

**Comment by arouinfar** [comment]
@samreid this is definitely an improvement. Since we cannot leverage the direction of the electrons, I don't have any ideas for how to address the odd behavior described in https://github.com/phetsims/circuit-construction-kit-common/issues/508#issuecomment-538125486. I think this'll have to do. Tagging #411 to document in the teacher tips.

**Comment by Nibbos** [comment]
Hi. Working with d.c. circuits and determining V-I characteristics for ohmic resistors requires ammeters to display negative current when polarity of battery is reversed. Students can then plot V versus I and determine R from 1/gradient of the graph.
Can negative currents be indicated on the ammeters just as negative voltage appear on the voltmeters, please?
Thanks 
Conor
