### ISSUE TITLE
User request: adjustable range of hertz values

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/circuit-construction-kit-common#517]
> I’m writing regarding an issue I have found with the AC+DC circuit construction kit: the AC source has a a limit of 2 hz. Given that frequency has a direct effect on the impedance of components, and that few circuits work at such values, I was thinking it might have been an oversight. An adjustable range of 0.1 to a few thousand Hz would be extremely useful.
> Also, I would like to make a few suggestions:
>- Add the option to include current sources in the designs.
>- It would be great if the simulators offered the option of using standardized symbols instead of the lifelike drawings of components. If you’re open to it, I’d be happy to contribute doing the necessary graphics in the required formats.
>- Being able to input the values directly would also be extremely practical.
>I have bought a few apps, and I find myself going back to your AC and DC labs, along with the other simulators, to be the most intuitive. They help me a lot in understanding the workings of electrical circuits.

**Comment by samreid** [comment]
We are discussing the range of the AC voltage source here: https://github.com/phetsims/circuit-construction-kit-common/issues/436

@arouinfar what would you like to do with the other ideas from this issue?  Perhaps split them out to separate issues and decide on them individually?

**Comment by arouinfar** [comment]
> I’m writing regarding an issue I have found with the AC+DC circuit construction kit: the AC source has a a limit of 2 hz. Given that frequency has a direct effect on the impedance of components, and that few circuits work at such values, I was thinking it might have been an oversight. An adjustable range of 0.1 to a few thousand Hz would be extremely useful.

This will be discussed in #436 

> Add the option to include current sources in the designs.

An ideal current source can be a useful mathematical tool, but it is not an actual circuit component and would somewhat violate the "kit" branding of the sim. While there are many [implementations](https://en.wikipedia.org/wiki/Current_source#Implementations) of real current sources, they go way beyond the scope of CCK.  

> It would be great if the simulators offered the option of using standardized symbols instead of the lifelike drawings of components. If you’re open to it, I’d be happy to contribute doing the necessary graphics in the required formats.

It looks like this user is unaware of schematic mode. It is also possible that are referring to IEC schematic symbols when they say "standard", but that is being discussed in #429.

> Being able to input the values directly would also be extremely practical.

While I agree, we don't have a way to support keyboard entry. It's also not touch-compatible, so we generally have done text entry through the use of a keypad. IMO, keypad entry would be far more clunky than using a NumberControl.

@oliver-phet can you reply to the user, thank them for their suggestions, and let them know about the schematic mode? Since the suggestions are being considered in other issues, please close this issue after you've replied.

**Comment by oliver-phet** [comment]
Email to user sent.
