### ISSUE TITLE
Charts should have zoom in/out buttons

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#536]
Charts should have zoom in/out buttons, like this:

![image](https://user-images.githubusercontent.com/679486/67392303-86922880-f55d-11e9-9180-c765fc48b571.png)

**Comment by samreid** [comment]
@arouinfar before I start on this, I want to double check on the layout.  It seems unfortunate to have to give up so much chart space for the zoom buttons.  Would it be possible to put them in the bottom left corner, which is already kind of an unused block of space?  Or maybe it's not too important to keep all of the chart horizontal space?  I'm happy to proceed as it's designed, just wanted to double check before I start.

**Comment by arouinfar** [comment]
We've discussed several options for the placement of the zoom buttons. In all the mockups below, the actual grid area is the same size, but the body of the tool becomes larger, depending on the zoom button placement.  These layouts all felt really awkward to us, which is why we settled for the layout shown in https://github.com/phetsims/circuit-construction-kit-common/issues/536#issue-511286522.

![image](https://user-images.githubusercontent.com/8419308/67724475-b9488080-f9a4-11e9-878f-9b73a4ab92e2.png)

> Would it be possible to put them in the bottom left corner, which is already kind of an unused block of space?

I'm not sure there's enough space to put them there without changing the dimensions of the tool body pretty significantly. Only one button will fit in that space.
![image](https://user-images.githubusercontent.com/8419308/67724843-f95c3300-f9a5-11e9-8039-7aed1b488d6a.png)

Another thing we should be careful about is the proximity to the time axis. These buttons do not affect the horizontal scaling at all, but placing the buttons near the bottom of chart may suggest that they do.

A similar option would be to place the zoom buttons on the left side of the tool, but that would really reduce the amount of space for i18n.
![image](https://user-images.githubusercontent.com/8419308/67724991-6a9be600-f9a6-11e9-92a8-2487779cf518.png)

My preference is still for the layout in https://github.com/phetsims/circuit-construction-kit-common/issues/536#issue-511286522. We do not need to remove chart space for this, but rather we would extend the bounds of the tool body.

**Comment by samreid** [comment]
One more question.  Should the "minus" button be on top because it zooms out and makes the values larger?

**Comment by arouinfar** [comment]
@samreid I think we generally keep the zoom in button on the top or right, so I would leave things how they are in the mockup.

**Comment by samreid** [comment]
Thanks, I committed an initial version, please review on phettest for reference.  Some questions:

* Should number of decimal places depend on value or perhaps on zoom level?  We want to show -2 -1 0 1 2, but also -0.5, 0, 0.5, right?
* What should the zoom ranges be?  Should they be the same for the voltage chart and current chart?

**Comment by arouinfar** [comment]
Discussed in the 1/9/20 design meeting.

The zoom button placement looks good.
<img width="316" alt="Screen Shot 2020-01-09 at 2 48 49 PM" src="https://user-images.githubusercontent.com/8419308/72107734-32424d80-32ef-11ea-9b84-ec58fff8ebe8.png">

Currently the zoom levels increase by a factor of 10, with max voltage increasing from 1 V to 1000 V. These step sizes are too large. I will play with it a bit and make a recommendation, but we like the idea of scaling up by some constant factor. Perhaps x2 would be more appropriate.

Voltage values >= 1 (and 0) do not need any decimals. 

We decided against scaling the spacing between the horizontal gridlines for now.

**Comment by samreid** [comment]
Also, I wanted to let you know the API for the zoom ranges takes an array of ranges, rather than a fixed zoom scale factor that must be applied at every level.  So, for instance you could choose zoom levels like:

```
-10,10
-50,50
-100,100
-250,250
-500,500
```

etc.

**Comment by samreid** [comment]
Bumping priority in hopes to address this before Jan 23 dev release.

**Comment by arouinfar** [comment]
@samreid let's go with these zoom ranges.

```
-2, 2
-10, 10
-20, 20
-50, 50
-100, 100
-150, 150
-200, 200
-400, 400
-600, 600
-800, 800
-1000, 1000
-1200, 1200
```

For each range, there will be a gridline at the midpoint between zero/max and zero/min, which is the current behavior of the voltage chart. For example [-100, 100] would look like this:

![image](https://user-images.githubusercontent.com/8419308/72943579-a4755200-3d33-11ea-8ac1-84e4f7b8ced5.png)

Since all these values are whole numbers divisible by 2, we can drop the decimal point on the readout too.

**Comment by samreid** [comment]
The ranges were updated in this version:
https://phet-dev.colorado.edu/html/circuit-construction-kit-ac/1.0.0-dev.9/phet/circuit-construction-kit-ac_en_phet.html

@arouinfar can review in the dev version, but I'll need to leave this self-assigned to help me to make sure the gridlines behave properly after I update the chart transforms.

**Comment by arouinfar** [comment]
I'm really liking the new zoom levels!

**Comment by arouinfar** [comment]
On second thought... I identified ranges optimal for voltage, but didn't take current into account. Current values will generally be lower than the voltage values, so we may want to consider adding an additional level or two of zooming in, possibly [-0.5, 0.5]. This would be the only zoom level with decimal values, and ideally we could show the decimals here but not on other levels.

**Comment by samreid** [comment]
When I tried a range of -0.5 .. 0.5 with a gridline in the middle and one decimal place, it rounded the 0.25 to 0.3:
![image](https://user-images.githubusercontent.com/679486/93086513-793dcb00-f654-11ea-91bc-f5cebd19d206.png)

When I used 2 decimal places, it seemed jarring going from 0 decimal places to 2 decimal places:

![image](https://user-images.githubusercontent.com/679486/93086600-9a9eb700-f654-11ea-8359-7b3bb0934339.png)

![image](https://user-images.githubusercontent.com/679486/93086624-a1c5c500-f654-11ea-93e1-d17c4127ab89.png)

Next I tried 0.6, but it was odd having 0.3 be a midline:

![image](https://user-images.githubusercontent.com/679486/93086709-c0c45700-f654-11ea-88c2-3d439f9061f1.png)

Finally I tried a range of -0.4 to 0.4 which has a midline of 0.2, and that looked OK to me:

![image](https://user-images.githubusercontent.com/679486/93086801-e5203380-f654-11ea-9504-c00734eb5bef.png)

@arouinfar what do you think?

**Comment by samreid** [comment]
I opened a few side issues for other problems I noticed.  For this issue, reassigning to @arouinfar to review the preceding comment.  I committed -0.4 ... 0.4 to master if you want to review that behavior.
