### ISSUE TITLE
New Feature: Add play/pause/step controls

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/circuit-construction-kit-common#572]
In working with the sim for a webinar, I really wanted to be able to pause the sim to do some quantitative analysis of the charge time of a capacitor in an RC circuit. With things constantly changing, this was not possible.

**Comment by samreid** [comment]
It looks like the labels were lost in the transfer.

**Comment by samreid** [comment]
I published a dev version here and will request brief spot testing on slack
https://phet-dev.colorado.edu/html/circuit-construction-kit-ac/1.0.0-dev.10/phet/circuit-construction-kit-ac_en_phet.html

**Comment by arouinfar** [comment]
@samreid I'm noticing several issues with the sim behavior. I think most of it stems from the circuit not instantaneously updating while paused. Stepping forward fixes all of the issues described below (except for the ResetAllButton).

* The TimeControlNode doesn't respond to the ResetAllButton. If the sim is reset while paused, it stays paused rather than returning to the startup state.

There are some issues with the current representation when the sim is paused.
* Elements dragged out the carousel do not have visible electrons.
* If the circuit is broken, the conventional current arrows stay visible.
* If a component is moved the electrons/conventional arrows will be left behind.

Removing or editing components while paused doesn't always yield instantaneous changes (but I think it should).
* The current in the circuit remains non-zero when the circuit is broken.
* Build a battery/bulb circuit. Changing R will change the brightness (even though current reading doesn't update). Changing V does not change the brightness.
* Clearing an inductor/capacitor doesn't do anything.

**Comment by arouinfar** [comment]
@samreid I think the issue underpinning most of this is that the current doesn't update while paused. This can lead to all sort of buggy looking situations (many described above), including situations like this:

<img src="https://user-images.githubusercontent.com/8419308/78410085-9f047580-75c8-11ea-9e59-cda1301e91e6.png" width=200>

The Java version of the simulation also doesn't update the current until the step forward button is pressed. However, the Java version doesn't have the delocalized electron issue.

**Comment by samreid** [comment]
In slack I said:

> I don’t have a simple and elegant way to get the physics to update when things change when paused. However, simple cases seem like they work OK if I run the physics engine with a tiny tiny dt when paused.

@kathy-phet replied:

> That seems like a reasonable solution.

**Comment by samreid** [comment]
The above commit changes the code so that if no acceptable minimum dt is discovered above the threshold, then it does not run the physics at all for that step.  I set the "paused" dt to 5E-13, which would accumulate 0.001 seconds over one year.  I tested for 10 minutes or so and did not see any obvious physics problems.  I did see it print out "nonlinear" a few times in the console, which indicates this condition was met, but it didn't seem to produce detrimental behavior in the sim.  I fuzzed for about 20 minutes and didn't see trouble. I published a dev version here for review https://phet-dev.colorado.edu/html/circuit-construction-kit-ac/1.0.0-dev.12/phet/circuit-construction-kit-ac_en_phet.html

@kathy-phet @arouinfar and @KatieWoe, can you please take a look at your convenience?

**Comment by samreid** [comment]
@kathy-phet said:

> I tried it out and i didn’t see any trouble. I will ask @mattpen to post it. We can do some more testing but since it’s not failing on fuzz test that seems to have solved the issue @arouinfar and I saw.

**Comment by mattpen** [comment]
1.0.0-dev.12 has been posted at https://phet.colorado.edu/sims/html/circuit-construction-kit-ac/latest/circuit-construction-kit-ac_en.html

**Comment by arouinfar** [comment]
@samreid the behavior in the updated prototype looks good to me. I was unable to reproduce any of the issues described in https://github.com/phetsims/circuit-construction-kit-common/issues/572#issuecomment-608708226.

That said, I think this is an issue that QA should test fairly aggressively in the next round of testing.

**Comment by samreid** [comment]
I determined there was already an existing infrastructure for detecting circuit changes.  I added Capacitor and Inductor clear to that channel, and used it for determining when to step the model when paused.  It seems OK in local testing, and much better than listening to scenery input and accessibility events.  @arouinfar can you please test in master?

**Comment by arouinfar** [comment]
@samreid master seems ok to me, but we'll still need QA to thoroughly test this when it comes time.

**Comment by samreid** [comment]
In today's design meeting, we discovered that the dog bark or fuse trip does not happen while paused.  We looked in the code and did not see an obvious immediate way to remedy this.  Since it doesn't seem as important as updating the currents or light bulb brightness, we will document it in the teacher tips without further implementation work.

**Comment by samreid** [comment]
I marked this for QA testing.  Can you please test the play/pause/step controls in a variety of circuits?  Including but not limited to capacitors and inductors.  Please note the caveats in the prior comment.

**Comment by Nancy-Salpepi** [comment]
In the newest build (1.0.0-dev.20), the current updates when an object is removed, but not when an object is added. 

https://drive.google.com/file/d/1tuTHW02yBU82IHz0uoTymR90YTJ0iblG/view?usp=sharing

**Comment by Nancy-Salpepi** [comment]
@samreid I just updated my last comment so it is easier to see and reproduce

**Comment by samreid** [comment]
Thanks, I was able to reproduce the problem and the commit solves it for me.  @Nancy-Salpepi can you please verify?  Please close if the behavior is as we hope.

**Comment by Nancy-Salpepi** [comment]
I was no longer able to reproduce the problem on Master.
