### ISSUE TITLE
Voltmeter and Ammeter seismograph gridlines should scroll horizontally

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#604]
From https://github.com/phetsims/griddle/issues/31.  Note that this will be an option.  Some sims will need to have static gridlines.

**Comment by samreid** [comment]
I switched to a new implementation that supports grid lines scrolling.  @arouinfar can you please check that the charts are behaving properly (including but not limited to the grid lines scrolling)?  Also, I converted to use the new zoom buttons that were developed during Natural Selection.

Also, now that we have scrolling grid lines, do we still want the "double-headed" arrow that indicates the span?  Or do we want scrolling labels?

**Comment by arouinfar** [comment]
We discussed this in the 11/19/20 design meeting.

There was some debate about whether or not we should have scrolling or static gridlines. While static gridlines have better alignment with the scale indicator and have an oscilloscope-like feel, we ultimately decided to stick with scrolling gridlines so that measurements of DC elements don't look broken.

I don't think we need scrolling labels, and the time scale indicator is still clear enough. Zoom buttons are being discussed in #620. Closing.
