### ISSUE TITLE
CapacitorNode is probably creating far too many <canvas> elements, and also making the charges blurry

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#633]
CapacitorNode is probably creating far too many `<canvas>` elements, and also making the charges blurry.

**Comment by samreid** [comment]
I confirmed each CapacitorNode is creating a separate canvas element:

![image](https://user-images.githubusercontent.com/679486/103059077-46fc0d80-4561-11eb-9be4-01cb46c4073b.png)

**Comment by samreid** [comment]
On the other hand, each canvas is pretty small, and the simulation is limited to 10 capacitors.  With 1 capacitor out, I measured 54MB, and with all 10 out, I measured 58.1MB.  This seems within tolerable levels.

![image](https://user-images.githubusercontent.com/679486/103059294-eb7e4f80-4561-11eb-9e77-8e679a048ebe.png)

I don't think we should support both canvas and scenery-based renderers for capacitors, it is simplest to have one renderer and not have to change between them.  PlateChargeNode.js is currently 300 lines of code.  Perhaps we should leave it alone for now--this sim doesn't seem a strong enough reason to warrant rewriting or duplicating as scenery nodes.

Performance is a little sluggish with 10 capacitors out.

But charges are not too blurry:

![image](https://user-images.githubusercontent.com/679486/103059412-444de800-4562-11eb-9b7c-f0de0594d93c.png)

I'm not sure why this was originally written as canvas--perhaps capacitor lab basics required good performance on older hardware?

@arouinfar what do you think about limiting the number of capacitors to 6 or so to limit performance problems?  I should also note that rewriting in scenery wouldn't necessarily have better performance--it may have worse performance.

**Comment by arouinfar** [comment]
@samreid the charges look reasonable to me with all 10 capacitors in the play area. I don't think it's worth limiting the number of capacitors to 6 to sharpen the charge appearance. 
![image](https://user-images.githubusercontent.com/8419308/103565343-6fe3a300-4e7d-11eb-9395-f73f2fb397cf.png)


Since the performance with canvas is reasonable, I don't see any reason to take a gamble on scenery. Let's leave it the way it is. 

If we end up seeing serious performance issues on lower-end devices in QA, we can consider reducing the number of components, but I think it's a bit premature for that.
