### ISSUE TITLE
Z-ordering of light bulb is wrong

### ISSUE THREAD

**Issue by liam-mulhall** [phetsims/circuit-construction-kit-common#659]
For https://github.com/phetsims/QA/issues/605.

![File_000](https://user-images.githubusercontent.com/60749003/107100461-ad678300-67d1-11eb-9297-7cda869ae331.png)

Notice how the fire is behind the light bulb's metal portion, but in front of the light bulb's glass portion.

I've seen this on multiple platforms and it seems to be an issue in both the RC linked above and the published version.

EDIT: This seems to be a problem with the battery as well.

**Comment by brooklynlash** [comment]
I also noticed this with other objects covering the bulb:
![lightbulb1](https://user-images.githubusercontent.com/72031637/107260368-46c5ad80-69fb-11eb-99aa-69a5322c02e1.PNG)
![lightbulb2](https://user-images.githubusercontent.com/72031637/107260373-488f7100-69fb-11eb-84c6-a702a5a9c7b2.PNG)

**Comment by KatieWoe** [comment]
Noting that this does seem to happen in the published sim. I also noticed that the light lines seem layered behind other objects, even if the bulb is on top. This is also in the published sim.
<img width="167" alt="lightbehind" src="https://user-images.githubusercontent.com/41024075/107443213-a607e880-6af5-11eb-92b5-10095b3124f4.png">

**Comment by arouinfar** [comment]
Thanks @liam-mulhall @brooklynlash @KatieWoe!

This behavior has been around since the 1.0 release of CCK: DC, and I'm pretty sure it's been discussed before, though I couldn't track down the issue.

While it definitely looks weird, the z-ordering is a bit complicated in this sim and there likely isn't an easy fix. Generally speaking, electrons need to go on top of components. The light bulb is a bit of a special case in that the socket needs to go on top of the electrons, so there is actually a back/front to the artwork. The light bulb glass lives in the same layer as the other components (under the electrons) but because the socket needs to obscure the electrons, it can go on top of other components.

@samreid feel free to close this as wont-fix.

**Comment by samreid** [comment]
@arouinfar described the problem eloquently--at one point we tried to have each electron rendered "in the layer of the component it is in" but that led to problems when junctioning with another circuit element.  I think this should be closed.
