### ISSUE TITLE
Battery resistance should not go to zero

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#676]
In slack, @kathy-phet said:

> [a collaborator] pointed out an issue with the sim that we have tracked down to the battery having 0 ohms of resistance. Can you make it have a miniscule amount of resistance (similar or smaller than the tiny wire resistivity) in master so Amy and I can take a look at he behavior? Amy mentioned at sometimes we add battery resistance anyways, so logic might be there.

**Comment by samreid** [comment]
Fixed and ready for review/discussion.

**Comment by samreid** [comment]
At today's meeting, we surmised that the fix for https://github.com/phetsims/circuit-construction-kit-common/issues/284 would supercede this fix.  So we should revert this commit.

**Comment by samreid** [comment]
We found that reverting the change made it so that loops like https://github.com/phetsims/circuit-construction-kit-common/issues/284#issuecomment-794297660 have voltages but no resistance and are nonphysical, so we reverted that revert.

**Comment by samreid** [comment]
I reverted the ideal batteries and made sure the "Constrain battery resistance to be above 1E-8" code is in place, ready for @kathy-phet to take a look and advise.

**Comment by samreid** [comment]
@kathy-phet requested via email:

> Can you please publish a dev version of the one with just that first minimum battery resistance change we made 

Self-assigning and raising priority.

**Comment by samreid** [comment]
I tested the version in master and it has the initial commit from this issue: https://github.com/phetsims/circuit-construction-kit-common/commit/8327d6fa711b2db73137a4c6b8a9a5994527b024 and it does not have the "ideal wires" proposal from https://github.com/phetsims/circuit-construction-kit-common/issues/284#issuecomment-794297660.

However, in testing this circuit:

![image](https://user-images.githubusercontent.com/679486/111422029-a0349280-86b3-11eb-8abe-37c42d96f58d.png)

I did not see the expected behavior of equal currents through the parallel branches.  I inspected the values and found this is because the batteries each have internal resistance of 1E-8 whereas the wire segments that length have a resistance of 0.0000018 Ohms, much larger than that of the battery.  When I tried increasing the battery internal resistance, I did see the desired behavior where the current flowed equally through the parallel branches (this can be done with the advanced controls on the lab screen). Long story short, here's a dev version with those values:

https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.3.0-dev.1/phet/circuit-construction-kit-dc_en_phet.html

**Comment by samreid** [comment]
From slack:

Kathy Perkins
> OK, thanks. Can you make 2 more dev version that makes the battery resistance minimum 1e-7 and 1e-6 so I can compare the behavior these versions?

Sam Reid
> I published it using a query parameter:
> https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.3.0-dev.2/phet/circuit[…]truction-kit-dc_en_phet.html?batteryMinimumResistance=1E-7
> https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.3.0-dev.2/phet/circuit[…]truction-kit-dc_en_phet.html?batteryMinimumResistance=1E-6

Kathy Perkins
> Thanks!

Sam Reid
> Also, if we increase the battery resistance to 1E-6, we can turn the wire resistivity way down.  I tried dividing the wire resistivity by 1E6 and it had good behavior for the parallel batteries case.

**Comment by samreid** [comment]
On the last comment, here is a dev version that has a query parameter for the wire resistivity, and showing that ?wireResistivity=1E-11&batteryMinimumResistance=1E-6 works pretty well for this case:

![image](https://user-images.githubusercontent.com/679486/111518167-6c8d5300-871b-11eb-9c23-b222ce1e6919.png)

https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.3.0-dev.3/phet/circuit-construction-kit-dc_en_phet.html?wireResistivity=1E-11&batteryMinimumResistance=1E-6

If that battery resistance is high enough that it can introduce noise in simple measurements, maybe it can be turned down, and the resistivity turned down accordingly.

**Comment by kathy-phet** [comment]
This circuit seems to behave as if the minimum wire resistance is not length dependent anymore?
https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.3.0-dev.3/phet/circuit[…]t.html?wireResistivity=1E-11&batteryMinimumResistance=1E-6

![image](https://user-images.githubusercontent.com/5096804/111689979-4686b200-87f2-11eb-8f7a-9de574c38332.png)



The 2 paths for the wires have a 2/3 1/3 split of current with the 1/3 going through the path composed of 2 wires.
Overall though - this seems to be behaving pretty well... haven't found any really weird show stoppers but I didn't hammer at it a lot.

Sam replied: 
Maybe there is a threshold..?--I’ll take a look after my meetings are over

**Comment by kathy-phet** [comment]
I have played around with these relationships between battery and wire resistance. 

1) To get the desired behavior of parallel batteries, we want 
**default wire resistivity to be 10^-5 times lower than battery defaults**, as in
?wireResistivity=1E-11&batteryMinimumResistance=1E-6
in this one (1e-4 different) you still see wire length as detectably effecting current in this scenario ?wireResistivity=1E-9&batteryMinimumResistance=1E-5
![image](https://user-images.githubusercontent.com/5096804/111712509-611d5300-8813-11eb-8f39-70a481097461.png)

2) And we need wire resistivity to remain a function of length... that seems to be true if ?wireResistivity=1E-9, but not for 1e-10 or 1e-11, when you look at this kind of loop. If the wires are the made to be the same length, you should have the same current through them. When ?wireResitivity=1E-11 we seem to get a 1/3 2/3 split regardless of the length/path of the wires
![image](https://user-images.githubusercontent.com/5096804/111712765-e99bf380-8813-11eb-9e3d-4181f59b966d.png)

@samreid - TO DO would be to figure out why 1e-10 and 1e-11 on wire resistivity seem to treat a wire as having a minimum total resistance, and not just a function of length.

3) Finally, at batteryMinimumResistance=1E-5, a battery of 120V and a bulb of 0.2 ohms, we start to see the impact of the current (600 amps) on the battery voltage due to its internal resistance. So we would not want to go any higher in batteryMinimumResistance. 
![image](https://user-images.githubusercontent.com/5096804/111713136-95ddda00-8814-11eb-87eb-006fd2af75f9.png)

**Comment by samreid** [comment]
Excellent, thanks!  It looks like Wire resistance is getting clamped to a minimum value of 1E-8 in this code.  I’ll tinker with it once Gravity and Orbits is in RC.2.

https://github.com/phetsims/circuit-construction-kit-common/blob/2cbbc258f636101230b597055324fca0e2cb343c/js/model/Wire.js#L91-L96

**Comment by samreid** [comment]
I reduced the minimum wire resistance to 1E-14 and made it so that ?dev will output wire resistivities when they change.  I tested with wireResistivity=1E-11&batteryMinimumResistance=1E-6 and it seemed reasonable.

![image](https://user-images.githubusercontent.com/679486/111835038-0e4aa680-88ba-11eb-8fac-96ece31bc06e.png)


We could potentially reduce these numbers further if we want a safety net.  I'm not sure how to determine "how low is too low".   This seems at a good point for @kathy-phet and/or @arouinfar to test in master, or let me know if you prefer a dev version.

**Comment by kathy-phet** [comment]
@samreid - Can you build a new dev of this version? (that still has the query parameter options). Thanks!

**Comment by samreid** [comment]
I deployed https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.3.0-dev.6/phet/circuit-construction-kit-dc_en_phet.html?wireResistivity=1E-11&batteryMinimumResistance=1E-6, please adjust the query parameters accordingly.

**Comment by samreid** [comment]
@arouinfar and I wanted to understand the "worst case scenario" for when a student could potentially see effects of the battery resistance.  The worst case scenario (aside from shorting with a coin or paper clip) is a 0.1 ohm light bulb wired up to 4 maxed out high-voltage batteries and 10 maxed out normal batteries.  Here is how that works out:

![image](https://user-images.githubusercontent.com/679486/112536947-b6a5b280-8d73-11eb-914b-717b9ecf35ce.png)

That is, a total internal resistance of 1E-10 is the lowest internal resistance that could show up in reading in the user interface.  Distributing that across the 14 components is 1E-10/14 per component, which works out to 1E-10/14 = 7.14E-12 ohms per battery.

@kathy-phet previously argued that the wire resistance needs to be 1E-5 times lower than the battery voltage.

@arouinfar will do the same analysis to determine the highest possible wire resistance that will show decimal places in the user interface.

@samreid will turn down these numbers to see at which point the linear algebra fails.

**Comment by kathy-phet** [comment]
From another colleague: 

> This works perfectly for the parallel equal-voltage batteries driving a bunch of light bulbs in series and parallel. The currents and voltages shown on the meters obey Kirchhoff’s laws, even if the bulb resistances are as low as 0.1 ohms. 
> 
> The battery charger mode with unequal voltages work too if you add resistors in series with the batteries or use the advanced mode in the lab app.

**Comment by kathy-phet** [comment]
@samreid @arouinfar - I played with the high voltage scenarios here. Things work well when paired as makes sense - that high voltage bulb with high voltage battery. 

I think these numbers are working well (wireResistivity=1E-11&batteryMinimumResistance=1E-6). You do see an impact on the battery voltage if you have high voltage batteries and low ohm light bulbs. 

I would favor doing a maintenance release at this point with these values - since circuits is the topic of the spring so getting this fix out this week would be good/needed. What do you think about having QA do a couple hours of testing some more obscure circuits and then if nothing breaks doing the maintenance release with this one change.

**Comment by samreid** [comment]
On Thursday, @arouinfar and I determined the largest battery resistance which would start to appear in the user interface in a "worst case scenario".  By choosing a value below that threshold, we can prevent battery resistance from showing up to the user.  @arouinfar will perform and similar calculation for the wires.  Once that is complete, I would like to better understand and what point the linear algebra starts to fail--to do this, I'll turn down both the battery internal resistance and wire resistivity gradually until the linear algebra starts to exhibit failures.

I opened a milestone for moving forward with republishing with the resistance/resistivity improvements: https://github.com/phetsims/circuit-construction-kit-common/milestone/3

**Comment by arouinfar** [comment]
@kathy-phet @samreid I've been playing around with high-voltage batteries with regular resistors, and things are looking really weird to me.

1. Build a circuit with 4 high-V batteries in series, all maxed out at 100,000 V (400,000 V total) and a standard resistor (10 Ohms).
2. Measure the current. It should be roughly 40,000 amps. However, in master and latest, the current is off by an order of magnitude and maxing out the battery resistance and changing the wire length does not change the current.

Master with ?wireResistivity=1E-11&batteryMinimumResistance=1E-6:
![image](https://user-images.githubusercontent.com/8419308/112912151-212c5a80-90b4-11eb-895d-ed3c0f9fca5f.png)
![image](https://user-images.githubusercontent.com/8419308/112912344-94ce6780-90b4-11eb-8f44-e879a0369d46.png)


Latest published version (1.2.1): 
![image](https://user-images.githubusercontent.com/8419308/112912124-0fe34e00-90b4-11eb-9fd8-19753585d6ab.png)
![image](https://user-images.githubusercontent.com/8419308/112912208-3e612900-90b4-11eb-83e7-b360370ec53b.png)


1.0.0:
![image](https://user-images.githubusercontent.com/8419308/112911951-ae22e400-90b3-11eb-8449-61cf46b76541.png)

**Comment by kathy-phet** [comment]
Yes, its the internal resistance of the battery -- at this current level it drops the battery voltage a lot when paired with a 0.1 ohm bulb. But it is fine when combined with a high resistance bulb. Overall, I'd rather live with this behavior than with the other issues with regular parallel batteries.

**Comment by kathy-phet** [comment]
@samreid - If you can take the numbers lower for the minimum wire resistance, then you can try that. I don't know when that breaks in terms of the math processing algorithms.

**Comment by arouinfar** [comment]
Perhaps this is a naive calculation, but I expected the current to be along the lines of 400000/(10 + 4E-6). I see that the voltage drop across the resistor is ~44444 V so the measured current is following Ohm's Law, but I don't understand why the battery internal resistance causes the actual voltage to differ so greatly.

**Comment by kathy-phet** [comment]
@arouinfar - Looking at the cases from above more closely, I think the behavior there is related to the fact that we separately increased battery resistance at some current threshold in order to get zero current passing through a parallel connect bulb in order to get the expected behavior of "turning off the light". I think we could actually back out that change - and just have this one change - because I think the behavior would naturally be correct now with this ratio of batter resistance to wire resistance. But we would have to check that. I need to find the issue.

**Comment by arouinfar** [comment]
> I think the behavior there is related to the fact that we separately increased battery resistance at some current threshold in order to get zero current passing through a parallel connect bulb in order to get the expected behavior of "turning off the light". 

Oh, good point @kathy-phet. That does seem like a likely culprit. I would agree that it's unnecessary now that batteries will always have some internal resistance.

Here's another case that seems really weird to me. 

1. Build a circuit with 1 high-V battery and 1 standard resistor. 
2. Gradually increase battery resistance and observe the current. For V < 40000 V (or I < 4000 amps) the circuit is well-behaved. 

<img src="https://user-images.githubusercontent.com/8419308/112913732-8cc3f700-90b7-11eb-85d6-c929bc6bd15b.png" width=250>
<img src="https://user-images.githubusercontent.com/8419308/112913749-9b121300-90b7-11eb-8dfe-97a0ecf78b2a.png" width=250>

**Comment by arouinfar** [comment]
@samreid can you investigate? Seems like there is an odd interaction with the changes made in https://github.com/phetsims/circuit-construction-kit-common/issues/245 are causing issues. Since batteries will always have internal resistance, we can probably revert the changes made in #245.

**Comment by kathy-phet** [comment]
You found the issue! Yay ...

**Comment by samreid** [comment]
- [ ] A reminder to write back to the client about this issue: https://github.com/phetsims/circuit-construction-kit-common/issues/677#issue-819126291

**Comment by samreid** [comment]
I reverted the changes in #245 and assigned it to @arouinfar for spot checking.

**Comment by kathy-phet** [comment]
@arouinfar - I had to disable cache to have this new version load properly. 
https://bayes.colorado.edu/dev/phettest/circuit-construction-kit-dc/circuit-construction-kit-dc_en.html?ea&brand=phet&wireResistivity=1E-11&batteryMinimumResistance=1E-6 

A few observations: 
1) For high voltage batteries maxed out, there is much less of a loss of voltage across them with default low ohm bulb. 
![image](https://user-images.githubusercontent.com/5096804/113060623-2221c280-916e-11eb-9dd0-c4dfb2238c4e.png)


2) If you short across the battery for default high voltage battery (1000V) and low ohm bulb (10 ohms), it still shows some brightness - and depends on how much wires you have because current is so big (on a 1000 V battery). 
![image](https://user-images.githubusercontent.com/5096804/113060275-a6c01100-916d-11eb-904a-9e37df5b5a4c.png)
But for default values, the high ohm bulbs do OK. 
![image](https://user-images.githubusercontent.com/5096804/113060459-e555cb80-916d-11eb-8ac5-95940138afe2.png)


3) If you take the 5 low-voltage batteries and max them out to 120V in series, and hook up a default bulb and then short the batteries, you see a very tiny lighting of the bulb (and 0.65V across the batteries). 
![image](https://user-images.githubusercontent.com/5096804/113059810-1c77ad00-916d-11eb-8c69-0cad54cb3bd5.png)

4) With bulb default, and 10 battery defaults, shorted, bulb still turns off: 
![image](https://user-images.githubusercontent.com/5096804/113061248-ff43de00-916e-11eb-9532-d0c5f6c8c13d.png)
But if you turn the resistance of the bulb down, or the battery voltages up, you will see the bulb start to light up. In this case if I turn ohmage down for the bulb, it just barely lights at 0.1 ohms. But if I increase the voltage of the batteries then you see it light more. 

This all seems like a good compromise place to me, basically showing what we want under the default conditions without anything that can't be explained for more complex situations.

**Comment by arouinfar** [comment]
After reading more carefully through #245, I realized that we were increasing the internal resistance of the battery when the current exceeds 4000 amps. That was how we were able to keep the bulbs turned off in extreme situations. However, this leads to the odd behavior I reported in https://github.com/phetsims/circuit-construction-kit-common/issues/676#issuecomment-809793527 and https://github.com/phetsims/circuit-construction-kit-common/issues/676#issuecomment-809801119.

I don't love how the bulbs tend to stay somewhat lit in @kathy-phet's examples in https://github.com/phetsims/circuit-construction-kit-common/issues/676#issuecomment-810600840 so I experimented more with `wireResistivity` and `batteryMinimumResistance`. 

Turning the wire resistivity down by an order of magnitude behaves quite nicely.
https://bayes.colorado.edu/dev/phettest/circuit-construction-kit-dc/circuit-construction-kit-dc_en.html?ea&brand=phet&wireResistivity=1E-12&batteryMinimumResistance=1E-6&screens=2

Here are a few exemplar circuits:
![image](https://user-images.githubusercontent.com/8419308/113085011-51e7bf00-919c-11eb-8d8e-2800c47e0f17.png)

**Comment by samreid** [comment]
@arouinfar are we still doing the analysis as described in https://github.com/phetsims/circuit-construction-kit-common/issues/676#issuecomment-809677868 to find the highest wire resistivity that can show up in the user interface, then to try to lower everything to understand the values where the linear algebra starts to fail?  Or did the short-circuited battery/light bulb case limit how far we can go?

**Comment by arouinfar** [comment]
> @arouinfar are we still doing the analysis as described in #676 (comment) to (a) find the lowest wire resistivity that shows up in the user interface, 

No, I don't think that approach is still appropriate. What I've done in https://github.com/phetsims/circuit-construction-kit-common/issues/676#issuecomment-810727725 is find a balance. A shorted bulb generally won't remain lit and the internal resistance won't show up in the values except in extreme cases.

**Comment by kathy-phet** [comment]
This setting looks good to me ... 
https://bayes.colorado.edu/dev/phettest/circuit-construction-kit-dc/circuit-construction-kit-dc_en.html?ea&brand=phet&wireResistivity=1E-12&batteryMinimumResistance=1E-6

And it also passes this other test of having the 1 wire and 2 wire parallel paths. These are dependent on pathlength, and don't show that oddity we saw before we turned down min wire resistance. If you make them the same length they will converge to 0.45 and 0.45 amps. 
![image](https://user-images.githubusercontent.com/5096804/113141080-79637980-91e6-11eb-80a7-0aa35fa1fd71.png)

**Comment by samreid** [comment]
I updated the constants and this version is ready for testing.

**Comment by arouinfar** [comment]
@samreid I tested circuits similar to those in https://github.com/phetsims/circuit-construction-kit-common/issues/676#issuecomment-810727725 and https://github.com/phetsims/circuit-construction-kit-common/issues/676#issuecomment-811012072 and things are behaving as expected.

**Comment by phet-steele** [comment]
Looks good in phetsims/QA/issues/633.
