### ISSUE TITLE
Schematic view appears to have a slight offset when making readings

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/circuit-construction-kit-common#756]
Found as part of https://github.com/phetsims/circuit-construction-kit-common/issues/748

When making a reading (such as with the current meter) if you switch to the schematic view you will sometimes lose your reading and it will not be immediately obvious why. It seems that if a current is being read in the normal view, switching the views should not change anything. We cannot expect students to always precisely place the meter over the centers of wires, so the thresholds should be the same between views. The video below show an example of this behavior

https://user-images.githubusercontent.com/4051174/137840496-27cbf2f3-31d6-409d-938e-5c80b87a2fab.mp4

**Comment by samreid** [comment]
It sounds like you are proposing that the schematic wires would have the same thickness as the lifelike view?  Just naively changing that wire width (but not of other circuit elements) to see what it would look like:

![image](https://user-images.githubusercontent.com/679486/138215534-e5ef942e-25bc-448d-9d32-f3b716085f82.png)

And here's changing the lifelike view to match the schematic dimension.
![image](https://user-images.githubusercontent.com/679486/138215601-fe637006-967e-4c20-bae5-d2bc95f91f22.png)

Maybe something in the middle would work?  I'm skeptical but that may just be because I'm used to the wide lifelike wires.

**Comment by samreid** [comment]
I expanded the hit area for capacitor to the highlighted region, it seems to match OK with the lifelike view:

![image](https://user-images.githubusercontent.com/679486/139754145-68d9842e-d40b-4030-8879-17936e0bb75c.png)

**Comment by samreid** [comment]
The pointer area for the fuse was shifted, and it was throwing off the results.  I corrected that, and set it to use the full bounds for schematic mode.  Both errors seem to be corrected, I'll create a dev version for review.

**Comment by samreid** [comment]
@ariel-phet can you please test in https://phet-dev.colorado.edu/html/circuit-construction-kit-ac/1.0.0-dev.43/phet/circuit-construction-kit-ac_en_phet.html

**Comment by ariel-phet** [comment]
@samreid I tested 1.0.0-dev.43 with a range of components. I think things are looking pretty good, closing
