### ISSUE TITLE
Overlapping electrons seen with parallel batteries

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/circuit-construction-kit-common#768]
It is pretty easy with a setup of parallel batteries and resistors to see some slightly odd behavior our of the electrons. You can get cases where the electrons appear to overlap for a bit and then one sort of slingshots away. This can lead to some uneven spacing conditions at times. Definitely not a showstopper, but worth being aware of.

Observed during testing of https://phet-dev.colorado.edu/html/circuit-construction-kit-ac/1.0.0-dev.40/phet/circuit-construction-kit-ac_en_phet.html

https://user-images.githubusercontent.com/4051174/139162774-d7125bd1-6dbf-4518-ab9e-7d2eae832d4d.mp4

**Comment by arouinfar** [comment]
The electron overlap is particularly noticeable in https://github.com/phetsims/circuit-construction-kit-common/issues/768#issue-1037948250, but it can happen at any parallel junction. The issue is that electrons don't get sorted into their new branch until their center reaches the center of the vertex. As electrons merge or are sorted into branches, they will accelerate to match up with the new speed. I don't think there's really anything to be done here, but I can make a note about this in the Teacher Tips.

![parallel](https://user-images.githubusercontent.com/8419308/139493885-80915765-dc90-4e26-a83e-0689825f8179.gif)
