### ISSUE TITLE
Should adjacent inductors have a constrained z-order?

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#771]
Discovered during #770, I saw the z-order of adjacent inductors making an incorrect 3d effect:

![image](https://user-images.githubusercontent.com/679486/139698833-b07bd292-f443-4363-aeb9-fd310faf2968.png)

I'm not sure how difficult this would be to fix, and I also don't think it would be pedagogically problematic, but I thought I'd run it past you to see if it warrants effort.

**Comment by arouinfar** [comment]
That screenshot definitely looks a bit weird @samreid, but I'm hesitant to suggest special-case z-ordering. There are other instances of odd-looking z-ordering because we chose simplicity in https://github.com/phetsims/circuit-construction-kit-common/issues/319 (wires under solder under other components).
<img src="https://user-images.githubusercontent.com/8419308/140099015-ff0b6bde-241b-495b-baa2-a94759ca7bc7.png" width=300>


In Java, the inductors look like this when connected in series:

<img src="https://user-images.githubusercontent.com/8419308/140098260-6a2cdd55-3c54-4ced-a7ce-33428a8dcc40.png" width=300>

Perhaps we could do the same in HTML5, by shifting the vertices further out so that they don't overlap.

I'll tag for design meeting to see what the team thinks.

**Comment by samreid** [comment]
Fixed and ready for review in next dev version.

**Comment by arouinfar** [comment]
It looks really nice @samreid!

**Comment by samreid** [comment]
Thanks, closing.
