### ISSUE TITLE
User suggestion: change schematic design of bulb

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/circuit-construction-kit-common#801]
Here's the original (?) design issue https://github.com/phetsims/circuit-construction-kit-common/issues/273

> I love the Circuit Construction Kit sims, but the way you have light bulbs shown when in schematic view is just asking for trouble with a room full of 14-yr old boys.
> 
> This is a diagram of a parallel circuit that will aid greatly in the teaching of circuits:
> ![66050957410__BF566F1A-2184-4373-8101-BA4D84911921](https://user-images.githubusercontent.com/5090275/144939891-880d279c-b27b-4057-ac91-716be8435a9d.jpg)
> And this is a diagram that will quickly cause a middle school class to devolve into chaos and pandemonium.
> ![IMG_4348](https://user-images.githubusercontent.com/5090275/144939915-1d0353d6-efcf-46dc-8ff1-6deb69d233e0.jpg)

**Comment by arouinfar** [comment]
@oliver-phet there really isn't anything we can do here. We are constrained by the current path. The electrons and conventional current arrows must travel on the same path regardless of whether the circuit is in lifelike or schematic mode. It is important the the lightbulb terminals are realistically placed on the bottom/side of the socket. We also want to accurately depict the flow of current through the filament. 

We are using the correct schematic symbol for the light bulb. However, we had to add the extenders so that the current is able to flow along the same path in both representations.

A few suggestions:

1. Build the circuit differently 
<img src="https://user-images.githubusercontent.com/8419308/145080022-fc833d2c-ebf1-4706-acaa-34e19f02c790.png" width=300>
2. Light bulbs in the schematic view do not glow, so they are functionally identical to the standard resistor. If the learning goal is to analyze circuit diagrams, perhaps they could instead use a standard resistor which would not have this issue.
<img src= "https://user-images.githubusercontent.com/8419308/145081436-2d00f0ba-c40b-452f-9db4-aac80e02093c.png" width=300>

**Comment by oliver-phet** [comment]
@arouinfar what about Sam's suggestion in https://github.com/phetsims/circuit-construction-kit-common/issues/273#issuecomment-295554469? I'm imagining if the schematic had an identical path as the lifelike view it could alleviate this phallic issue?

> What about keeping the same path as the filament of the light bulb, but drawing the circle across the top? That way we could keep the path geometry the same.

Here's a quick mockup using the filament path and aligning the "bulb" schematic on top. I think this could have a couple benefits:

1. The path of electrons/current can perfectly match the lifelike view (currently is different)
2. Reduces the phallic issue

![cckArtboard 1](https://user-images.githubusercontent.com/5090275/145112413-bea8b4d9-f797-44c7-8a9e-f2e3d4b654dc.png)

**Comment by oliver-phet** [comment]
@arouinfar I think I forgot to assign this issue back to you after my quick mockup. I think it has benefits beyond the phallic issue, but up to you to decide!

**Comment by arouinfar** [comment]
Since this can cause classroom disruption, similar to #882, it's worth considering for the current milestone. I think @oliver-phet's mockup is an improvement, but it might not completely eliminate the issue.

@samreid @matthew-blackman what do you recommend?

**Comment by samreid** [comment]
@matthew-blackman and I reviewed the issue, and our recommendation is to leave the design as it is.  We do not feel the proposal in https://github.com/phetsims/circuit-construction-kit-common/issues/801#issuecomment-988291705 addresses the problem, and we feel its asymmetrical wire layout is unfortunate.  We also don't feel there is a problem having a different electron path between lifelike and schematic.  Therefore, we recommend closing this issue.

**Comment by arouinfar** [comment]
Thanks @matthew-blackman @samreid, let's close.
