### ISSUE TITLE
Circuit element NumberDisplays have inconsistent font size

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/circuit-construction-kit-common#822]
I was demoing this sim yesterday and saw a small inconsistency in font size. The Frequency number control is inconsistent with the other control sizes. I think would be nice if we could match that to the other sizes and do a MR if easy. @arouinfar - Can you take a peak? And let me know if this was intentional or we just overlooked it previously? Thx.  
![image](https://user-images.githubusercontent.com/5096804/150557523-e8df22ca-e3e5-4f28-b4d4-cb2fe0742fab.png)

**Comment by arouinfar** [comment]
Summary:
- Circuit components added after CCK: DC 1.0 are styled differently.
- All resistance and voltage controls are collapsed into a single control in the published versions but will be decoupled for phet-io so we will have more control over pixel polishing.
- We should be using a consistent font size for these controls and will pixel polish as a part of the upcoming release.

Slack discussion:

>Amy Rouinfar  9:31 AM
It’s not just the frequency control. Resistance and Voltage NumberControls (which were the only controls in the 1.0 release of DC) are styled differently. They use a smaller font because we are spelling out volts and ohms (every other unit is abbreviated). Also, the NumberDisplay size is the same for both standard and high-V/high-R varieties so the font size is smaller due to the string lengths at max value. (edited) 
9:34
>With the work that SR is doing for iO, there won’t be a single resistance control shared by the resistor, bulb, high-R resistor, and high-R bulb, so we may have more freedom in the individual sizing.
>
>Kathy Perkins  9:42 AM
OK - I was thinking we just want the font size consistent. So if its smaller because it needs more space, we would just make them all match that same smaller size? Or make the text box bigger to fit the bigger size?
>
>Amy Rouinfar  9:45 AM
I agree, though I think the larger size is better and more readable when the sim is being projected. I wouldn’t bother with a MR since these NumberControls will be uncoupled for iO and we can pixel polish them for future release.
9:45
The inconsistencies in font have been around since CCK: DC 1.1 (when we added the fuse).
>
>Kathy Perkins  9:49 AM
>OK. We will polish with PhET-iO release.
>
>Sam Reid  9:49 AM
@arouinfar can you please move or summarize this conversation in #822?
9:50
Please also mark #822 for the phet-io milestone
>
>Amy Rouinfar  9:51 AM
Yes, will do
>
>Kathy Perkins  9:53 AM
@arouinfar - I do agree the bigger size is more readable and preferrable if we can design that.

**Comment by samreid** [comment]
@arouinfar and I took a look and suspect this may have been caused by maxWidth restrictions.  But we also observed that the maxWidth can extend over the tweakers if necessary (looks like it might be constrained just to the slider track).  I'll take a look.

**Comment by samreid** [comment]
CircuitElementNumberControl specifies maxWidth at 2 levels:

```ts
    const options = merge( {
      titleNodeOptions: {
        maxWidth: CircuitElementNumberControl.NUMBER_CONTROL_ELEMENT_MAX_WIDTH,
        font: CCKCConstants.DEFAULT_FONT
      },
      numberDisplayOptions: {
        maxWidth: 80,
        valuePattern: valuePattern,
        decimalPlaces: numberOfDecimalPlaces,
        textOptions: {
          font: CCKCConstants.DEFAULT_FONT
        }
      },
```

The different-length text under the same maxWidths can yield different sizes of text.  I'm not aware of how to match sizes across different components.  Do we want to match the fonts only of things that can be seen at the same time, or of all editors within one screen, or all editors across all screens?  Also, does this problem affect CCK DC?

**Comment by arouinfar** [comment]
Thanks @samreid. I'll tag this for design meeting.

There are a few things we can consider.
* The NumberDisplay for the high-V/R and standard batteries/resistors/bulbs appears to be the same size. This creates a lot of unnecessary blank space for standard components.
* Spelling out `volts` and `ohms` adds a lot of characters. Can we use abbreviations instead? We use abbreviations elsewhere in the voltmeters, ammeters, battery resistance slider, and current rating slider.

>  Also, does this problem affect CCK DC?

Yes, it does affect CCK: DC. The styling of the Current Rating NumberDisplay is ideal, but not so great for batteries, resistors, and bulbs.

**Comment by matthew-blackman** [comment]
In design meeting we decided that this is worth about 15 minutes of work to try and make it look as uniform as possible. A robust solution is preferred, but this issue does not warrant a large overhaul of the UI logic.

**Comment by samreid** [comment]
Increasing the number display max width a little seemed to help a lot.  After that change, the fuse looks like:

<img width="394" alt="image" src="https://user-images.githubusercontent.com/679486/208448617-9d44e7fc-dde3-448e-8a5f-41e109fb286f.png">

High voltage battery looks like:
<img width="384" alt="image" src="https://user-images.githubusercontent.com/679486/208448692-ef4889ee-c8cb-4cf9-870d-2d7ff376016b.png">

stringTest=dynamic doubled
<img width="387" alt="image" src="https://user-images.githubusercontent.com/679486/208448810-153213df-9160-4f77-9e2c-1ce0c26dcc09.png">


stringTest=double (to show when volts gets a lot longer)
<img width="390" alt="image" src="https://user-images.githubusercontent.com/679486/208449284-55d6cfd8-81c8-4ebf-b13e-95b198f707f8.png">


quadrupled
<img width="408" alt="image" src="https://user-images.githubusercontent.com/679486/208448869-aeff172d-d7b4-48d1-ac34-9bf617fa235d.png">

x8
<img width="408" alt="image" src="https://user-images.githubusercontent.com/679486/208448924-4e550d96-de56-4b5a-b335-63ee328bdb83.png">

In AC
<img width="543" alt="image" src="https://user-images.githubusercontent.com/679486/208448974-03993ed1-ffaf-4a27-bfa8-016865a8091f.png">

doubled
<img width="537" alt="image" src="https://user-images.githubusercontent.com/679486/208449029-55f35182-32bc-4266-bb1f-9199fa2e0812.png">

quadrupled
<img width="559" alt="image" src="https://user-images.githubusercontent.com/679486/208449083-f8fb025c-929f-44c0-95a9-1bb7c7f08ea7.png">

@arouinfar does this seem good enough?

**Comment by arouinfar** [comment]
Nice! This is definitely an improvement @samreid, thanks! I think this addresses the original issues, so I'll close.
