### ISSUE TITLE
Add `isSelectedProperty` to circuit elements

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-common#835]
Discovered in #797 

Vertices have `selectedProperty` to indicate when the vertex has been selected (to be renamed `isSelectedProperty` in #834). This would be helpful for circuit elements as well. 

@samreid this can wait until the full release.

**Comment by samreid** [comment]
Due to other considerations (including but may not be limited to the circuit element edit panels), the selected circuit element is tracked through `Circuit.selectedCircuitElementProperty`.  This is instrumented and visible in the tree as `circuitConstructionKitDc.labScreen.model.circuit.selectedCircuitElementProperty`.  Is this sufficient, or should we add a readonly version in CircuitElement itself?

**Comment by arouinfar** [comment]
Ah, good point @samreid. I think `circuit.selectedCircuitElementProperty` is preferable. Is there a reason why it doesn't provide the phetioID of selected vertices?

**Comment by samreid** [comment]
`circuit.selectedCircuitElementProperty` indicates which circuit element is selected.  For instance, in this case, `resistor_0` is selected:

<img width="691" alt="image" src="https://user-images.githubusercontent.com/679486/154778094-ee997305-c44b-4516-b1c5-355fd7dc39b1.png">


By clicking on the resistor in the tree, you can see which vertices it is connected to:

<img width="754" alt="image" src="https://user-images.githubusercontent.com/679486/154778184-46185e23-755c-467b-84ce-f84e39219823.png">

@arouinfar does that seem reasonable?  Can this issue be closed?

**Comment by arouinfar** [comment]
Thanks @samreid. We can continue the discussion over in #850 since your proposal in https://github.com/phetsims/circuit-construction-kit-common/issues/850#issuecomment-1045446290 would make this issue moot.
