### ISSUE TITLE
In line ammeters that are connected to each other may show current when not connected to anything else

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/circuit-construction-kit-common#846]
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/772.
Fairly minor. On the lab screen, if you connect three or more in-line ammeters, the ones in the middle will read 0, rather than a dash or a question mark. This happens in the published version as well.

**Visuals**
Published:
<img width="450" alt="published_ammeters" src="https://user-images.githubusercontent.com/41024075/152853981-0d673465-a466-4088-8cb2-f6e8f307175a.png">
Dev version:
<img width="638" alt="dev_ammeters" src="https://user-images.githubusercontent.com/41024075/152854003-428383d2-e7a9-4f8b-be9d-515da301ba7e.png">

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Circuit Construction Kit: DC‬
URL: https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.3.0-dev.14/phet/circuit-construction-kit-dc_all_phet.html
Version: 1.3.0-dev.14 2022-02-01 01:48:26 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36
Language: en-US
Window: 1280x649
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by arouinfar** [comment]
Thanks @KatieWoe. This is not a bug, but by design. The ammeters on the edges have null readings (only one probe connected) and so we display a dash, which we generally use to convey null readings in other sims. This is a change from the `?` used in the previously published version, see https://github.com/phetsims/circuit-construction-kit-common/issues/757. The ammeters in the middle all have valid readings (both sides connected) but there isn't any current flowing, so the reading is 0.
