### ISSUE TITLE
Fuse blows repeatedly in State wrapper

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/circuit-construction-kit-common#849]
**Test device**
iPad Air 2

**Operating System**
15.2

**Browser**
Safari

**Problem description**
For https://github.com/phetsims/qa/issues/772
In the State Wrapper, the fuse will continuously blow in the downstream sim. I was able to reproduce this using my MacBook + Safari. When I looked into this in the Studio wrapper, if I blew the fuse before launching the sim (not sure why anyone would want to do that), the sim launches showing the fuse being blown. 

**Steps to reproduce**
1. In the State Wrapper: Make a circuit with a fuse. 
2. Increase the battery voltage until the fuse blows (or decrease the current rating)

**Visuals**
![fuseblows](https://user-images.githubusercontent.com/87318828/152883236-2949784c-98bd-497c-859a-7616ac8a66aa.gif)

**Comment by arouinfar** [comment]
@samreid this looks like a bug that can negatively impact the client's usage. I recommend we try fixing this before sending the client another version, but if that's not feasible it should be documented as a known bug.

**Comment by samreid** [comment]
Good find, QA team!  The commit addresses https://github.com/phetsims/circuit-construction-kit-common/issues/849#issuecomment-1032811084.  

For https://github.com/phetsims/circuit-construction-kit-common/issues/849#issue-1126577466, my understanding is that the Fuse is a dynamic element, and created fresh each frame.  It is created with `isTrippedProperty=false` by default.  Then when the state sets its value to `isTripped=true` that triggers the animation.  This may not be a problem for clients in practice, since there is no use case for clients using the state wrapper with students.  In studio this bug would present as the fuse just tripping when the customized sim starts up (though I did notice that animation is at the wrong coordinates).  But maybe we can say "only play the animation if the fuse trips when we aren't setting phet-io state".  @arouinfar should we try that, or do we sometimes need to show the fuse trip animation when setting phet-io state?  Please advise.

**Comment by arouinfar** [comment]
Thanks for the explanation @samreid. I wasn't sure if this bug would also manifest if a student submits the state of the sim as a solution. If this bug is unlikely to show up in that case, I'll update the doc we shared with the client. We can defer the discussion about the tripped fuse animation until we resume work on the next milestone.

**Comment by samreid** [comment]
Sounds good, I'll move to the next milestone.  Please feel free to move it back if you still need to update the doc.

**Comment by samreid** [comment]
Fixed, and working well in testing launching a studio state with a tripped fuse.  Closing.
