### ISSUE TITLE
Updates to ammeters and voltmeters

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-common#857]
@samreid I'd like to make the following tweaks to the ammeters & voltmeters:

- [x] Add linked property (`model.meters.*`) to corresponding view elements (`view.meterNodes.*`)
- [x] Replicate `view.meterNodes.ammeter*.probeTextNode` in the series ammeter
- [x] Replicate `model.meters.ammeter*.currentProperty` in the series ammeter

**Comment by samreid** [comment]
> Replicate view.meterNodes.ammeter*.probeTextNode in the series ammeter

This was more complicated because SeriesAmmeterNode previously had an independent implementation of the readout.  But it was very nice to unify it with the other readouts.  This aligned the tandems, and it is ready for review.  Please also check for what things should be `phetioFeatured`--in the commit `circuitConstructionKitDc.labScreen.view.circuitNode.seriesAmmeterNodeGroup.archetype.readoutPanel.visibleProperty` disappeared and I'm not sure if its replacement(s) are or should be featured.

**Comment by arouinfar** [comment]
Thanks @samreid. This all looks good, but the comments I made in regards to `readoutText` in https://github.com/phetsims/circuit-construction-kit-common/issues/854#issuecomment-1273846549 apply here. 

It looks like you made things `phetioFeatured` within the sim code. Not sure if that will be the way forward or not, since https://github.com/phetsims/phet-io/issues/1873 hasn't been resolved. Additionally, the `phetioFeatured` overrides are still preliminary, and will need updating before release (assuming we still are using overrides), see #836.

The remaining questions/TODOs are tracked elsewhere, so I'll go ahead and close this issue.
