### ISSUE TITLE
Back to back battery shading looks incorrect

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#89]
![image](https://cloud.githubusercontent.com/assets/679486/15102599/87c16f00-155e-11e6-8041-a55289c8e696.png)

@arouinfar please advise

**Comment by arouinfar** [comment]
@samreid is it possible to have the highlight move as the component rotates? I could provide you with artwork without the highlight, and then the highlight could be drawn in code.  I vaguely remember this being done in another sim, but I'm blanking on which one. 

Alternatively, there could be two versions of the battery, so that in the situation you've shown, both batteries would have the highlight at the top. For example, when the battery is oriented horizontally with its positive terminal pointing to the right, the artwork would have the highlight at the top. Once the battery is rotated just past +/- 90*, the artwork would swap so that the highlight is on the other side. The shading will still be somewhat off, but you wouldn't encounter the situation like the one in the screenshot above.

By the way, this is not something you need to address for the MVP @samreid.

**Comment by samreid** [comment]
> Alternatively, there could be two versions of the battery,

This is the strategy we are trying out for the wires, but it yields situations which look odd.  In this case, one wire is at the critical angle minus epsilon, the other is at the critical angle plus epsilon.  This problem could be exaggerated for batteries.
![image](https://cloud.githubusercontent.com/assets/679486/15113349/f66203d2-15b0-11e6-9b8a-253ea87c6bb0.png)

We drew a dynamic highlight for the Probe sensor node, but that was easier since the entire thing was programmatically generated and there is no other texture.  Not sure if we could manage the same effect with the battery/wires or if what we choose here must eventually apply to inductors, resistors, energy components, etc.

Other options:
* Don't show highlight at all in this sim (or in circuit components).
* Vertically center the highlight and make it vertically symmetric.

@arouinfar thoughts?

**Comment by arouinfar** [comment]
> Don't show highlight at all in this sim (or in circuit components).

I don't particularly like this option because it doesn't feel PhET-like, stylistically speaking.

> Vertically center the highlight and make it vertically symmetric.

This seems like a better approach. Most components are relatively thin, so a center highlight may not look that odd. 

@ariel-phet can you take a look at this issue and comment?

**Comment by ariel-phet** [comment]
A centered highlight definitely seems like the way to go for the moment. Perhaps not stylistically perfect, but at least consistent and simple. For the MVP that seems like a good compromise, and we can revisit as a pixel polishing issue later.

I would leave wires "as is" for the moment...they are thin enough and the situation seems rare enough for the moment to no warrant deep attention. Batteries however will likely go into the configuration shown at the beginning of the issue,

**Comment by samreid** [comment]
@arouinfar would you like to update the AI files?

**Comment by arouinfar** [comment]
Thanks for your feedback @ariel-phet! 

@samreid, I've emailed you an updated .ai file for the battery.

**Comment by samreid** [comment]
Looks better @arouinfar, I'll commit shortly.

![image](https://cloud.githubusercontent.com/assets/679486/21510312/1efc70ac-cc4f-11e6-92d2-f2553125b052.png)

**Comment by samreid** [comment]
Closing.
