### ISSUE TITLE
Deleting a vertex using the keyboard in the state wrapper did not update

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#901]
Discovered in https://github.com/phetsims/circuit-construction-kit-common/issues/839, Deleting a vertex using the keyboard in the state wrapper did not update the upstream sim.  But the vertex split in the downstream sim.  So the upstream sim was left in a broken state.

**Comment by jessegreenberg** [comment]
This is happening because sim code in the downstream sim is setting focus to something within its window. So key presses are getting dispatched to the downstream sim instead of the upstream sim. The problem goes away if you focus the upstream sim with the dev tools.

I believe https://github.com/phetsims/joist/issues/750 is the right long term fix for this issue. When focus follows the mouse and the upstream sim receives focus as you interact with it, this problem won't happen. That will be an "epic" level issue and isn't slated for work soon. In a zoom call today a short term workaround was identified but if that doesn't remain an acceptable fix, please let me know.

**Comment by samreid** [comment]
Today's workaround seems like it is working well, and good enough to unblock publication.  Closing.
