### ISSUE TITLE
Household components leave empty space in the toolbox carousel when used

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/circuit-construction-kit-common#903]
@samreid and I were investigating #630 and agreed that the carousel having empty spaces is not a great UX generally, including when 'singleton' components like the household objects are added to the stage. A relatively low-cost solution would be to leave a faded out placeholder graphic when a component is 'used up', similar to the following:

Current:
![Screen Shot 2022-12-01 at 10 44 45 AM](https://user-images.githubusercontent.com/108756567/205096559-2f737292-da2b-40ee-b4e1-a67d09af378d.png)

Idea:
![Screen-Shot-2022-11-30-at-3 56 14-PM](https://user-images.githubusercontent.com/108756567/205097749-0560673b-4320-4b4e-bdba-5132be54502d.png)

What do you think @arouinfar?

**Comment by arouinfar** [comment]
I really like the idea of disabling the icon rather than hiding it. We do something similar in Function Builder, albeit with a more custom look:

<img width="152" alt="image" src="https://user-images.githubusercontent.com/8419308/205120063-2fd989f4-e364-443e-aa60-8d3f1f2f0af1.png">

Seems like we should consider a generalizable solution for all carousels. Perhaps these options could work:
* Leave an empty hole
* Apply the `DISABLED_OPACITY` scenery constant
* Something sim-specific and custom (like Function Builder)

**Comment by arouinfar** [comment]
> The real bulb starts grayed out instead of invisible, we thought that seemed OK but wanted to check since that is a difference?

I don't love this, but I think it has to do with the general UX/flow of the non-ohmic bulbs.

The grayscale icon implies that all of the bulbs are out in the play area, but in reality, real bulbs are disabled until the "Add Real Bulbs" checkbox is checked. Said checkbox appears in a closed-by-default AccordionBox on the other side of the screen. Users will likely encounter the real bulb in the carousel before experimenting with the Advanced options, and it could cause some confusion.

I think we could instead consider making non-ohmic bulbs opt-out instead of opt-in. It would involve: 
 * Removing "Add Real Bulbs" checkbox from the Advanced AccordionBox.  
 * Replacing `addRealBulbs` query parameter with something like `hideRealBulbs`.
 * Using `hideRealBulbs` should completely remove the icon from the carousel, not just make it grayscale. (Is this doable @samreid @matthew-blackman?)

This is a bigger decision and should involve the larger design team.

> Do we like the grayscale part or not?

I like it! I think using grayscale rather than `DISABLED_OPACITY` is a nice touch. Removing all of the components of a particular type leaves behind a ghost to indicate its place, and grayscale feels appropriate. Applying `DISABLED_OPACITY` has a slightly different implication, in my opinion.

**Comment by samreid** [comment]
> Using hideRealBulbs should completely remove the icon from the carousel, not just make it grayscale. (Is this doable @samreid @matthew-blackman?)

Yes, that seems straightforward.

**Comment by samreid** [comment]
For now, I restored the prior behavior where the real bulb icon does not appear in the toolbox until it has been selected in the advanced toolbox.  

> I think we could instead consider making non-ohmic bulbs opt-out instead of opt-in.

Should this be discussed in a separate issue?  It's unclear whether this recommendation was due to the grayed out real bulb in the toolbox or for other reasons. I wanted to clarify that those are independent, as shown in the commit.

**Comment by samreid** [comment]
@matthew-blackman and I reviewed the existing implementation and agreed the carousel is working nicely, including for ohmic bulbs.  Remaining work will be done in https://github.com/phetsims/circuit-construction-kit-common/issues/910, closing this issue.
