### ISSUE TITLE
Number of decimal places in meter readings should be constant

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/circuit-construction-kit-common#963]
While investigating https://github.com/phetsims/circuit-construction-kit-common/issues/961, @samreid and I came across the changing number of decimal places in the voltmeter and ammeter readings. This was discussed in https://github.com/phetsims/circuit-construction-kit-dc/issues/125 and the conclusion was to typically show 2 decimal places for current and voltage readouts in the play area, but if it is a smaller value, between 0.02 and 0.001, then it should show 3 decimal places.

This creates pedagogical issues as well as conflicts with PatternStringProperty.

Pedagogical issues:
- Changing the number of decimal places in an instrument implies that the instrument precision is changing, which is not the case in the real world. If a student were using a real voltmeter or ammeter, they would need to contend with the fact that any readings less than half of the minimum increment will read out as zero. I believe that this sim should match this real-world behavior rather than try to shield students from it.
- This does not fundamentally solve the issue of a meter reading zero for small measurements, but simply defers the issue to the thousandths place instead of the hundredths place.
- This will cause problems with the data fluency initiative for CCK, since instrument precision is a major focus of that redesign.

Conflicts with PatternStringProperty:
- While trying to convert voltageReadoutProperty to a PatternStringProperty, @samreid and I found that the number of decimal places is being set in createVoltageReadout within CCKCUtils, which prevents us from having this value available to pass into PatternStringProperty. It would be possible to make PatternStringProperty use a function that dynamically determines the number of decimal places based on a value, but we believe this would create unnecessary complexity and be rarely used.
- After investigation, we have concluded that the only way to utilize PatternStringProperty to create dynamic strings in the meter readouts would be to extend PatternStringProperty or create a custom implementation for voltmeter and ammeter readings

**Comment by matthew-blackman** [comment]
Update: @samreid and I have successfully worked around the PatternStringProperty conflicts in #961, so this conversation can focus around what is best pedagogically.

**Comment by arouinfar** [comment]
Thanks @matthew-blackman. You bring up some really great points. I think one of the main tensions in https://github.com/phetsims/circuit-construction-kit-dc/issues/125 was related to situations where the current was clearly non-zero, but would be measured as zero (such as an extreme bulb with a regular battery). We often treat these situations as opportunities to discuss measurement precision/limitations, but at the time, we felt this was insufficient for younger learners. We may have also been partially motivated by the hand and dog -- we didn't want to measure zero current because it could present a dangerous idea.  

However, we no longer include the dog or hand in the simulation. I would also advise younger learners to use `screens=1` (though we didn't start advertising `screens` until after 1.0 was published).

I can think of a few options:
1. Always display current to the hundredths place. (We lose out on precision that may be helpful with the extreme components.)
2. Always display current to the thousandths place. (Not the friendliest option for younger learners.)
3. Use different precision on the Intro and Lab screens. The audience and learning goals for these two screens are different, so this feels acceptable. This somewhat circumvents @matthew-blackman's concern about changing precision, as you could argue that the meters (or settings) are different on the two screens. 

I prefer option (3), but I'm curious to hear what others think.

**Comment by matthew-blackman** [comment]
After discussing with @kathy-phet, we will set the precision of the meters to the hundredths place, and investigate further to locate any potential issues with wire resistivity, bulb brightness, and high resistance circuits.

**Comment by matthew-blackman** [comment]
This is fully implemented. I tested it out with all sensors and the behavior looks correct. @arouinfar this is ready for your review. If all looks good then this issue can be closed.

**Comment by arouinfar** [comment]
The behavior looks good in master, thanks!

When we discussed yesterday, there was some concern that bulbs would remain lit even though ammeters read `0.00 A`. Here's what it looks like the current is just below the rounding threshold:

![image](https://user-images.githubusercontent.com/8419308/220712255-864f0f92-4cb6-4beb-8736-b5cacf0a7101.png)

The rays are not noticeable unless you zoom in, which seems perfectly acceptable. 
![image](https://user-images.githubusercontent.com/8419308/220712124-4d7ddef1-6371-4858-b259-8bfbc7639ff3.png)

**Comment by matthew-blackman** [comment]
I should note that in the above commit I removed the following comment due to @arouinfar's feedback above.
`// Show 3 decimal places so that current can still be seen with a glowing high-resistance bulb`

**Comment by zepumph** [comment]
Yes perfect thanks. I appreciate it.
