### ISSUE TITLE
Non-contact ammeters are poorly supported in virtual-lab

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-common#976]
Tangentially related to https://github.com/phetsims/qa/issues/900 and discovered while reviewing https://github.com/phetsims/circuit-construction-kit-common/issues/865.

CCK: DC - Virtual Lab is nearly identical to its parent sim. There are two primary differences:
1. It's a single-screen sim, consisting of just the Lab screen (`screens=2`)
2. Non-contact ammeters are excluded.

Non-contact ammeters are still visible in the Studio Tree and can be found under:
* `circuitConstructionKitDcVirtualLab.labScreen.model.meters` 
* `circuitConstructionKitDcVirtualLab.labScreen.view.meterNodes`
* `circuitConstructionKitDcVirtualLab.labScreen.view.sensorToolbox`

Clients can use `isActiveProperty` to add the non-contact ammeter to the play area of the sim. However, it is not possible to make them visible in the toolbox. `view.sensorToolbox.noncontactAmmeterToolNode.visibleProperty` is `true` by default, but no icon appears in the toolbox. I assumed that the default would be `false` and clients could set it to `true` to give students access to non-contact ammeters.

I see two options
1. Fix `view.sensorToolbox.noncontactAmmeterToolNode.visibleProperty` so it has the expected behavior -- default `false`, but clients can set it to `true` to add non-contact ammeters to the toolbox. This would be consistent with how we generally handle the PhET-iO instrumentation of derivative sims.
2. Completely uninstrument everything related to the non-contact ammeters in virtual-lab. If clients want to use non-contact ammeters, they can use cck-dc with `screens=2`. 

I am fine with either option, so I'll leave it up to @samreid and @matthew-blackman to decide.

**Comment by matthew-blackman** [comment]
@samreid @zepumph @arouinfar and I discussed this, and agree that all non-contact ammeter tandems should be removed from studio for CCK DC-Virtual Lab. We plan to uninstrument this so that users cannot encounter any possibly buggy behavior by adding these sensors in the Virtual Lab version of the sim.

If clients want to show non-contact ammeters in the Lab screen, they can use the standard version of the sim with screens=2.

**Comment by matthew-blackman** [comment]
This is ready for review. @arouinfar please confirm that all noncontact ammeter tandems are showing correctly in both sims and all screens.

**Comment by samreid** [comment]
For the code review, specifying `showNoncontactAmmeters: true,` [js/intro/view/IntroScreenView.ts](https://github.com/phetsims/circuit-construction-kit-dc/commit/b1e346952f64de297d9adc6d4eab3cf62394eb8d#diff-63d01b55d0b3cd09f82727f7398c43e99570fd0bf944e7f2c257223fd8a9dfed) could lead to trouble since it allows a model to create noncontact ammeters but the view to not show them.  So I think the solution for that part would be to assign it to the model and use something like `model.isShowNoncontactAmmeters`.

For this code: could we skip creating them altogether if `showNoncontactAmmeters` is false?  Or does that cause problems?

```ts
    this.ammeters = [
      new Ammeter( providedOptions?.showNoncontactAmmeters ? metersTandem.createTandem( 'ammeter1' ) : Tandem.OPT_OUT, 1 ),
      new Ammeter( providedOptions?.showNoncontactAmmeters ? metersTandem.createTandem( 'ammeter2' ) : Tandem.OPT_OUT, 2 )
    ];

```

Everything else in the code review looks great.  Reassigning to @matthew-blackman for the code review issues. Leaving assigned to @arouinfar to review the runtime behavior and API.

**Comment by matthew-blackman** [comment]
@samreid I think this warrants a final review before closing, given the issues we explored in the patch above.

**Comment by arouinfar** [comment]
I no longer see any reference to the non-contact ammeters in the cck-dc-virtual-lab tree. So from a design perspective, everything looks good.

**Comment by matthew-blackman** [comment]
@samreid and I reviewed the most recent commit and agree that this issue can be closed.
