### ISSUE TITLE
phetioID for battery on lab screen in incorrect in Examples doc

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/circuit-construction-kit-common#983]
On the lab screen, the battery is called "Right Battery." 
<img width="973" alt="Screenshot 2023-03-02 at 3 24 53 PM" src="https://user-images.githubusercontent.com/87318828/222545244-34c40418-450b-4208-a842-9305c14e15f5.png">

The links in the Examples doc are incorrect. 
<img width="973" alt="Screenshot 2023-03-02 at 3 25 33 PM" src="https://user-images.githubusercontent.com/87318828/222545334-a557257c-0e02-4eac-930e-6e213faef10e.png">

**Comment by arouinfar** [comment]
Good find @Nancy-Salpepi! 

Just a note that this issue could have possibly been prevented by https://github.com/phetsims/phet-io-sim-specific/issues/21.

 When creating the examples doc, I copied the `phetioIDs` for the Intro screen and swapped out `introScreen` for `labScreen`. I think it's reasonable to manipulate `phetioIDs` in this way, and it's likely something a client would do. We should be using consistent tandem names across screens.

I've not been fond of the term `rightBattery` and suggested changing it in #853. I do not think the arguments for leaving as-is in #853 still hold. We should optimize the names for the existing flavors of CCK. We do not currently have any reason to distinguish between "left" and "right" batteries, but if we do in the future, migration rules for renaming tandems are simple.

@samreid or @matthew-blackman please remove "right" from `labScreen.view.circuitElementToolbox.carousel.items.rightBatteryToolNode` so that it is simply `batteryToolNode` and matches the equivalent element on the Intro Screen.

**Comment by samreid** [comment]
Renamed in the commits, please review.

**Comment by samreid** [comment]
Incorrect URL on that commit ⬆️

**Comment by arouinfar** [comment]
Looks good, thanks @samreid.

**Comment by samreid** [comment]
For QA, please check that the sim battery/icon is now called "battery" instead of "rightBattery".

**Comment by Nancy-Salpepi** [comment]
"Right battery" is now" battery" in rc.3
Closing.
